In [1]:
from pathlib import Path
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load
#
import os
from utils.benchmarks import BENCHMARKS_TO_PATHS

if "IREWR_WITH_MODIN" in os.environ and os.environ["IREWR_WITH_MODIN"] == "True":
    import os

    os.environ["MODIN_ENGINE"] = "ray"
    import ray

    ray.init(
        num_cpus=int(os.environ["MODIN_CPUS"]),
        runtime_env={"env_vars": {"__MODIN_AUTOIMPORT_PANDAS__": "1"}},
    )
    import modin.pandas as pd
else:
    import pandas as pd
# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [4]:
### cell 0 ###

benchmark_name = "billionaires-statistics-2023"
data = pd.read_csv(Path(BENCHMARKS_TO_PATHS[benchmark_name]).parent / "input" / "Billionaires Statistics Dataset.csv")
factor = 8
data = pd.concat([data] * factor, ignore_index=True)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21120 entries, 0 to 21119
Data columns (total 34 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   finalWorth                                  21120 non-null  int64
 1   category                                    21120 non-null  object
 2   personName                                  21120 non-null  object
 3   age                                         20600 non-null  float64
 4   country                                     20816 non-null  object
 5   city                                        20544 non-null  object
 6   source                                      21120 non-null  object
 7   industries                                  21120 non-null  object
 8   countryOfCitizenship                        21120 non-null  object
 9   organization                                2600 non-null   object
 10  selfMade                                    21120 non-null  bool
 11  status                                      21120 non-null  object
 12  gender                                      21120 non-null  object
 13  birthDate                                   20512 non-null  object
 14  lastName                                    21120 non-null  object
 15  firstName                                   21096 non-null  object
 16  title                                       2712 non-null   object
 17  date                                        21120 non-null  object
 18  state                                       6024 non-null   object
 19  residenceStateRegion                        5976 non-null   object
 20  birthYear                                   20512 non-null  float64
 21  birthMonth                                  20512 non-null  float64
 22  birthDay                                    20512 non-null  float64
 23  cpi_country                                 19648 non-null  float64
 24  cpi_change_country                          19648 non-null  float64
 25  gdp_country                                 19808 non-null  object
 26  gross_tertiary_education_enrollment         19664 non-null  float64
 27  gross_primary_education_enrollment_country  19672 non-null  float64
 28  life_expectancy_country                     19664 non-null  float64
 29  tax_revenue_country_country                 19656 non-null  float64
 30  total_tax_rate_country                      19664 non-null  float64
 31  population_country                          19808 non-null  float64
 32  latitude_country                            19808 non-null  float64
 33  longitude_country                           19808 non-null  float64
dtypes: bool(1), float64(14), int64(1), object(18)
memory usage: 5.3+ MB

In [5]:
### cell 1 ###

data.head(5)

,finalWorth,category,personName,age,country,city,source,industries,countryOfCitizenship,organization,...,cpi_change_country,gdp_country,gross_tertiary_education_enrollment,gross_primary_education_enrollment_country,life_expectancy_country,tax_revenue_country_country,total_tax_rate_country,population_country,latitude_country,longitude_country
0,211000,Fashion & Retail,Bernard Arnault & family,74.0,France,Paris,LVMH,Fashion & Retail,France,LVMH Moët Hennessy Louis Vuitton,...,1.1,"$2,715,518,274,227",65.6,102.5,82.5,24.2,60.7,67059887.0,46.227638,2.213749
1,180000,Automotive,Elon Musk,51.0,United States,Austin,"Tesla, SpaceX",Automotive,United States,Tesla,...,7.5,"$21,427,700,000,000",88.2,101.8,78.5,9.6,36.6,328239523.0,37.090240,-95.712891
2,114000,Technology,Jeff Bezos,59.0,United States,Medina,Amazon,Technology,United States,Amazon,...,7.5,"$21,427,700,000,000",88.2,101.8,78.5,9.6,36.6,328239523.0,37.090240,-95.712891
3,107000,Technology,Larry Ellison,78.0,United States,Lanai,Oracle,Technology,United States,Oracle,...,7.5,"$21,427,700,000,000",88.2,101.8,78.5,9.6,36.6,328239523.0,37.090240,-95.712891
4,106000,Finance & Investments,Warren Buffett,92.0,United States,Omaha,Berkshire Hathaway,Finance & Investments,United States,Berkshire Hathaway Inc. (Cl A),...,7.5,"$21,427,700,000,000",88.2,101.8,78.5,9.6,36.6,328239523.0,37.090240,-95.712891

In [6]:
### cell 2 ###

data.describe()

,finalWorth,age,birthYear,birthMonth,birthDay,cpi_country,cpi_change_country,gross_tertiary_education_enrollment,gross_primary_education_enrollment_country,life_expectancy_country,tax_revenue_country_country,total_tax_rate_country,population_country,latitude_country,longitude_country
count,21120.000000,20600.000000,20512.000000,20512.000000,20512.000000,19648.000000,19648.000000,19664.000000,19672.000000,19664.000000,19656.000000,19664.000000,1.980800e+04,19808.000000,19808.000000
mean,4623.787879,65.140194,1957.183307,5.740250,12.099844,127.755204,4.364169,67.225671,102.858520,78.122823,12.546235,43.963344,5.102053e+08,34.903592,12.583156
std,9832.611000,13.255845,13.280249,3.709452,9.917183,26.448238,3.623118,21.339627,4.710139,3.729435,5.367669,12.143134,5.541468e+08,17.000492,86.747657
min,1000.000000,18.000000,1921.000000,1.000000,1.000000,99.550000,-1.900000,4.000000,84.700000,54.300000,0.100000,9.900000,3.801900e+04,-40.900557,-106.346771
25%,1500.000000,56.000000,1948.000000,2.000000,1.000000,117.240000,1.700000,50.600000,100.200000,77.000000,9.600000,36.600000,6.683440e+07,35.861660,-95.712891
50%,2300.000000,65.000000,1957.000000,6.000000,11.000000,117.240000,2.900000,65.600000,101.800000,78.500000,9.600000,41.200000,3.282395e+08,37.090240,10.451526
75%,4200.000000,75.000000,1966.000000,9.000000,21.000000,125.080000,7.500000,88.200000,102.600000,80.900000,12.800000,59.100000,1.366418e+09,40.463667,104.195397
max,211000.000000,101.000000,2004.000000,12.000000,31.000000,288.570000,53.500000,136.600000,142.100000,84.200000,37.200000,106.300000,1.397715e+09,61.924110,174.885971

In [7]:
### cell 3 ###

country_names = data[
    "country"
].value_counts()  # List of how many billionaires there are in the country

In [8]:
### cell 4 ###

country_names

country
United States               6032
China                       4184
India                       1256
Germany                      816
United Kingdom               656
                            ...
Turks and Caicos Islands       8
Tanzania                       8
Bahrain                        8
Andorra                        8
Armenia                        8
Name: count, Length: 78, dtype: int64

In [9]:
### cell 5 ###

data_100 = data.loc[:100, ["finalWorth", "category", "country"]]

In [10]:
### cell 6 ###

data_100_category = data_100["category"].value_counts()

In [11]:
### cell 7 ###

data_usa = data[
    data["country"] == "United States"
]  # We focus on billionaires based in United States

In [12]:
### cell 8 ###

data_usa_category = data_usa["category"].value_counts()
data_usa_category

category
Finance & Investments         1520
Technology                    1128
Food & Beverage                592
Fashion & Retail               504
Real Estate                    408
Media & Entertainment          296
Sports                         280
Energy                         280
Healthcare                     272
Manufacturing                  224
Service                        152
Diversified                    104
Automotive                      96
Gambling & Casinos              48
Telecom                         40
Construction & Engineering      40
Logistics                       40
Metals & Mining                  8
Name: count, dtype: int64

In [13]:
### cell 9 ###

data_usa_city = data_usa["city"].value_counts()
print(data_usa_city)
data_usa_city.info()

city
New York          792
San Francisco     296
Los Angeles       272
Palm Beach        168
Dallas            160
                 ...
Gallatin            8
Jupiter Island      8
San Carlos          8
Arcadia             8
Pottsville          8
Name: count, Length: 268, dtype: int64
<class 'pandas.core.series.Series'>
Index: 268 entries, New York to Pottsville
Series name: count
Non-Null Count  Dtype
--------------  -----
268 non-null    int64
dtypes: int64(1)
memory usage: 4.2+ KB

In [14]:
### cell 10 ###

data.head(5)

,finalWorth,category,personName,age,country,city,source,industries,countryOfCitizenship,organization,...,cpi_change_country,gdp_country,gross_tertiary_education_enrollment,gross_primary_education_enrollment_country,life_expectancy_country,tax_revenue_country_country,total_tax_rate_country,population_country,latitude_country,longitude_country
0,211000,Fashion & Retail,Bernard Arnault & family,74.0,France,Paris,LVMH,Fashion & Retail,France,LVMH Moët Hennessy Louis Vuitton,...,1.1,"$2,715,518,274,227",65.6,102.5,82.5,24.2,60.7,67059887.0,46.227638,2.213749
1,180000,Automotive,Elon Musk,51.0,United States,Austin,"Tesla, SpaceX",Automotive,United States,Tesla,...,7.5,"$21,427,700,000,000",88.2,101.8,78.5,9.6,36.6,328239523.0,37.090240,-95.712891
2,114000,Technology,Jeff Bezos,59.0,United States,Medina,Amazon,Technology,United States,Amazon,...,7.5,"$21,427,700,000,000",88.2,101.8,78.5,9.6,36.6,328239523.0,37.090240,-95.712891
3,107000,Technology,Larry Ellison,78.0,United States,Lanai,Oracle,Technology,United States,Oracle,...,7.5,"$21,427,700,000,000",88.2,101.8,78.5,9.6,36.6,328239523.0,37.090240,-95.712891
4,106000,Finance & Investments,Warren Buffett,92.0,United States,Omaha,Berkshire Hathaway,Finance & Investments,United States,Berkshire Hathaway Inc. (Cl A),...,7.5,"$21,427,700,000,000",88.2,101.8,78.5,9.6,36.6,328239523.0,37.090240,-95.712891

In [15]:
### cell 11 ###

category_list = list(data.category.unique())
category_list

['Fashion & Retail',
 'Automotive',
 'Technology',
 'Finance & Investments',
 'Media & Entertainment',
 'Telecom',
 'Diversified',
 'Food & Beverage',
 'Logistics',
 'Gambling & Casinos',
 'Manufacturing',
 'Real Estate',
 'Metals & Mining',
 'Energy',
 'Healthcare',
 'Service',
 'Construction & Engineering',
 'Sports']

In [16]:
### cell 12 ###

data.finalWorth = data.finalWorth.astype(float)
worth_average = []
for i in category_list:
    x = data[data["category"] == i]
    worth_ratio = sum(x.finalWorth) / len(x)
    worth_average.append(worth_ratio)
data2 = pd.DataFrame({"category_list": category_list, "worth_average": worth_average})
new_index = (data2["worth_average"].sort_values(ascending=False)).index.values
new_data = data2.reindex(new_index)

In [17]:
### cell 13 ###

# data3 =data.dropna(axis="index",how="any",inplace=False) # ı created new df because so many nan values was exist
# for cudf doesnt return the same df
data3 = data.dropna(axis=0, how="any", subset=data.columns)

In [18]:
### cell 14 ###

data3.head()

,finalWorth,category,personName,age,country,city,source,industries,countryOfCitizenship,organization,...,cpi_change_country,gdp_country,gross_tertiary_education_enrollment,gross_primary_education_enrollment_country,life_expectancy_country,tax_revenue_country_country,total_tax_rate_country,population_country,latitude_country,longitude_country
1,180000.0,Automotive,Elon Musk,51.0,United States,Austin,"Tesla, SpaceX",Automotive,United States,Tesla,...,7.5,"$21,427,700,000,000",88.2,101.8,78.5,9.6,36.6,328239523.0,37.09024,-95.712891
2,114000.0,Technology,Jeff Bezos,59.0,United States,Medina,Amazon,Technology,United States,Amazon,...,7.5,"$21,427,700,000,000",88.2,101.8,78.5,9.6,36.6,328239523.0,37.09024,-95.712891
3,107000.0,Technology,Larry Ellison,78.0,United States,Lanai,Oracle,Technology,United States,Oracle,...,7.5,"$21,427,700,000,000",88.2,101.8,78.5,9.6,36.6,328239523.0,37.09024,-95.712891
4,106000.0,Finance & Investments,Warren Buffett,92.0,United States,Omaha,Berkshire Hathaway,Finance & Investments,United States,Berkshire Hathaway Inc. (Cl A),...,7.5,"$21,427,700,000,000",88.2,101.8,78.5,9.6,36.6,328239523.0,37.09024,-95.712891
5,104000.0,Technology,Bill Gates,67.0,United States,Medina,Microsoft,Technology,United States,Bill & Melinda Gates Foundation,...,7.5,"$21,427,700,000,000",88.2,101.8,78.5,9.6,36.6,328239523.0,37.09024,-95.712891

In [19]:
### cell 15 ###

data3.info()  # in the new df we have 238 rows for each column

<class 'pandas.core.frame.DataFrame'>
Index: 1904 entries, 1 to 21088
Data columns (total 34 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   finalWorth                                  1904 non-null   float64
 1   category                                    1904 non-null   object
 2   personName                                  1904 non-null   object
 3   age                                         1904 non-null   float64
 4   country                                     1904 non-null   object
 5   city                                        1904 non-null   object
 6   source                                      1904 non-null   object
 7   industries                                  1904 non-null   object
 8   countryOfCitizenship                        1904 non-null   object
 9   organization                                1904 non-null   object
 10  selfMade                                    1904 non-null   bool
 11  status                                      1904 non-null   object
 12  gender                                      1904 non-null   object
 13  birthDate                                   1904 non-null   object
 14  lastName                                    1904 non-null   object
 15  firstName                                   1904 non-null   object
 16  title                                       1904 non-null   object
 17  date                                        1904 non-null   object
 18  state                                       1904 non-null   object
 19  residenceStateRegion                        1904 non-null   object
 20  birthYear                                   1904 non-null   float64
 21  birthMonth                                  1904 non-null   float64
 22  birthDay                                    1904 non-null   float64
 23  cpi_country                                 1904 non-null   float64
 24  cpi_change_country                          1904 non-null   float64
 25  gdp_country                                 1904 non-null   object
 26  gross_tertiary_education_enrollment         1904 non-null   float64
 27  gross_primary_education_enrollment_country  1904 non-null   float64
 28  life_expectancy_country                     1904 non-null   float64
 29  tax_revenue_country_country                 1904 non-null   float64
 30  total_tax_rate_country                      1904 non-null   float64
 31  population_country                          1904 non-null   float64
 32  latitude_country                            1904 non-null   float64
 33  longitude_country                           1904 non-null   float64
dtypes: bool(1), float64(15), object(18)
memory usage: 507.6+ KB

In [20]:
### cell 16 ###

data3.countryOfCitizenship.unique()  # and 238 billionaires in usa, others deleted.

array(['United States', 'Canada', 'Germany', 'Israel', 'Norway',
       'Ireland', 'Turkey', 'France'], dtype=object)