<a id="1"></a>
# <div style="text-align:center; padding:20px;color:white;margin:0;font-size:35px;font-family:Serif;display:fill;border-radius:5px;background-color:#FF4455;overflow:hidden"><b>🗽NewYork City Airbnb EDA📈</b></div>

![](https://miro.medium.com/fit/c/160/112/0*I09pD975_KRExbNY)

<a id="1"></a>
# <div style="padding:20px;color:white;margin:0;font-size:35px;font-family:Serif;text-align:left;display:fill;border-radius:5px;background-color:#FF4455;overflow:hidden"><b>⭕Introduction</b></div>

<div style="font-family:Serif;background-color:#FFD5E1; padding:30px; font-size:17px">
<b>New York City is a bustling metropolis located in the northeastern region of the United States. It is often referred to as the "City That Never Sleeps" due to its vibrant nightlife and round-the-clock activity. The city is home to a diverse population of over 8 million people, making it one of the most densely populated areas in the country.<br><br>New York City is known for its iconic landmarks, such as the Statue of Liberty, the Empire State Building, and Central Park. It is also renowned for its world-class museums, restaurants, and shopping destinations. From the bright lights of Times Square to the trendy neighborhoods of Brooklyn, New York City offers something for everyone.<br><br>Airbnb is a popular online platform that allows travelers to book unique accommodations directly from local hosts. In New York City, Airbnb offers a wide range of options, including apartments, lofts, and private rooms. Many of these listings are located in trendy neighborhoods, providing visitors with a local experience that is different from staying in a traditional hotel. However, it is important to note that New York City has strict laws regulating short-term rentals, and travelers should ensure that their Airbnb booking complies with local regulations.</b>

<a id="1"></a>
# <div style="padding:20px;color:white;margin:0;font-size:35px;font-family:Serif;text-align:left;display:fill;border-radius:5px;background-color:#FF4455;overflow:hidden"><b>⭕Table of Contents</b></div>

<div style="font-family:Serif;color:#DB3A49; padding:10px; font-size:20px">
    ⭕ Import<br>
    ⭕ Check Missing Value<br>
    ⭕ Feature Engineering<br>
    ⭕ EDA<br>
    ⭕ Price<br>
    ⭕ Suburb _ Each Suburb price in Newyork<br>
    ⭕ Price_Main bnb service in 50~250 dollars<br>
    ⭕ Neighbourhood<br>
    ⭕ Reviews<br>
    ⭕ Calculated_Host_Listings_Count<br>
    ⭕ availability_365

<a id="1"></a>
# <div style="padding:20px;color:white;margin:0;font-size:35px;font-family:Serif;text-align:left;display:fill;border-radius:5px;background-color:#FF4455;overflow:hidden"><b>⭕Import</b></div>

In [1]:
# %load_ext cudf.pandas
# Import Visualization FrameWork Tools
import pandas as pd
import numpy as np

# import missingno as msno
import time

In [2]:
s = time.time()

In [3]:
df = pd.read_csv("./AB_NYC_2019.csv")
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [4]:
print("Shape of DataFrame: ", df.shape)

Shape of DataFrame:  (48895, 16)

In [5]:
factor = 10
df = pd.concat([df] * 10)

In [6]:
# check null-value and each columns' dtype to do EDA.
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 488950 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              488950 non-null  int64
 1   name                            488790 non-null  object
 2   host_id                         488950 non-null  int64
 3   host_name                       488740 non-null  object
 4   neighbourhood_group             488950 non-null  object
 5   neighbourhood                   488950 non-null  object
 6   latitude                        488950 non-null  float64
 7   longitude                       488950 non-null  float64
 8   room_type                       488950 non-null  object
 9   price                           488950 non-null  int64
 10  minimum_nights                  488950 non-null  int64
 11  number_of_reviews               488950 non-null  int64
 12  last_review                     388430 non-null  object
 13  reviews_per_month               388430 non-null  float64
 14  calculated_host_listings_count  488950 non-null  int64
 15  availability_365                488950 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 63.4+ MB
None

<a id="1"></a>
# <div style="padding:20px;color:white;margin:0;font-size:35px;font-family:Serif;text-align:left;display:fill;border-radius:5px;background-color:#FF4455;overflow:hidden"><b> ⭕Check Missing Value</b></div>

In [7]:
# msno.matrix(df,figsize=(20,4),fontsize=10)

<a id="1"></a>
# <div style="padding:20px;color:white;margin:0;font-size:35px;font-family:Serif;text-align:left;display:fill;border-radius:5px;background-color:#FF4455;overflow:hidden"><b>⭕Feature Engineering</b></div>

## <div style="font-family:Serif;color:#DB3A49; padding:10px; font-size:35px">Drop unnecessary Columns

In [8]:
df = df.drop(["id", "last_review", "name", "host_name"], axis=1)
df.head()

,host_id,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
0,2787,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,0.21,6,365
1,2845,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,0.38,2,355
2,4632,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,1,365
3,4869,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,4.64,1,194
4,7192,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,0.10,1,0

<div style="font-family:Serif;background-color:#FFD5E1; padding:30px; font-size:17px">
<b>Column "availability_365" means number of days when listing is available for booking. Its means that the total number of days the accommodation operates during the year. Here, a value of 0 means an accommodation that has not been operated for one year, so it is removed.</b>

In [9]:
df = df.drop(df[df["availability_365"] == 0].index, axis=0)
df = df.reset_index()
df.head()

,index,host_id,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
0,0,2787,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,0.21,6,365
1,1,2845,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,0.38,2,355
2,2,4632,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,1,365
3,3,4869,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,4.64,1,194
4,5,7322,Manhattan,Murray Hill,40.74767,-73.97500,Entire home/apt,200,3,74,0.59,1,129

## <div style="font-family:Serif;color:#DB3A49; padding:10px; font-size:35px">Fill Missing Value

In [10]:
df["reviews_per_month"] = df["reviews_per_month"].fillna(0)
df.head()

,index,host_id,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
0,0,2787,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,0.21,6,365
1,1,2845,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,0.38,2,355
2,2,4632,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,0.00,1,365
3,3,4869,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,4.64,1,194
4,5,7322,Manhattan,Murray Hill,40.74767,-73.97500,Entire home/apt,200,3,74,0.59,1,129

In [11]:
df.isnull().sum()

index                             0
host_id                           0
neighbourhood_group               0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
dtype: int64

In [12]:
df.shape

(313620, 13)

<div style="font-family:Serif;color:#DB3A49; padding:10px; font-size:20px">Clean

<a id="1"></a>
# <div style="padding:20px;color:white;margin:0;font-size:35px;font-family:Serif;text-align:left;display:fill;border-radius:5px;background-color:#FF4455;overflow:hidden"><b>⭕EDA</b></div>

<a id="1"></a>
# <div style="padding:10px;color:white;margin:0;font-size:35px;font-family:Serif;text-align:left;display:fill;border-radius:5px;background-color:#FF4455;overflow:hidden"><b>⭕Price</b></div>

In [13]:
# def eda_map(df,feature, ax):
#     plt.figure(figsize=(15,15))
#     image = Image.open("/kaggle/input/new-york-city-airbnb-open-data/New_York_City_.png") # Load the image
#     df.plot(kind='scatter', x='longitude', y='latitude', label='AirBnB On service', c=str(feature), ax=ax, # Create the scatter plot
#             cmap=plt.get_cmap('jet'), colorbar=True, alpha=0.4, zorder=5, s=1)
#     ax.imshow(image,extent=[-74.258, -73.7, 40.49,40.92]) # Set the extent of the image

In [14]:
# plt.figure(figsize=(20,15))
# ax = plt.gca()
# eda_map(df,'price',ax)

<div style="font-family:Serif;background-color:#FFD5E1; padding:30px; font-size:17px"><b>We can know that all of the air bnb service place from Above Graph. But it is hard to judge that which place is hot/cheap/expensive etc more information. So I seperate these parts with some features.</b>

In [15]:
# # check outlier in price
nyc_sub = ["Manhattan", "Brooklyn", "Queens", "Bronx", "Staten Island"]

# x = nyc_sub
# y = []
# for i in x:
#     y.append(df[df['neighbourhood_group']==i]['price'].values.tolist())
# plt.figure(figsize=(20,8))
# plt.boxplot(y,notch=True, whis=2.5)
# plt.xticks([1, 2, 3,4,5], x);

## <div style="font-family:Serif;color:#DB3A49; padding:10px; font-size:35px">Price_Breakdown in $100 dollar$ units from $0$-$1000 dollar$

<div style="font-family:Serif;background-color:#FFD5E1; padding:30px; font-size:17px"><b>At first, seperate the place with price. It is found that most of the prices are distribute on 0~1000 dollar. So I breakdown in 100 dollar units from 0-1000dollar to see the price distribute more speciffically.</b>

In [16]:
# price_range = 0
# fig, axes = plt.subplots(nrows=5, ncols=2, figsize=(18, 22))
# for row in axes:
#     for ax in row:
#         if price_range < 1000:
#             eda_map(df[(df['price'] > price_range*100) & (df['price'] < (price_range+1)*100)], 'price',ax)
#             ax.set_title(f"Price Range ${price_range*100} - ${(price_range+1)*100} Total Amount: {len(df[(df['price'] > price_range*100) & (df['price'] < (price_range+1)*100)])}")
#             price_range += 1

# plt.tight_layout()

<div style="font-family:Serif;background-color:#FFD5E1; padding:30px; font-size:17px"><b>Most of the BnB service price is in 50~250 dollar.</b>

### <div style="font-family:Serif;color:#DB3A49; padding:10px; font-size:30px">Mapping

<div style="font-family:Serif;background-color:#FFD5E1; padding:30px; font-size:17px"><b>Through the previous visualization, 50-250 was mainly distributed. Subsequent more diverse visualizations add a more detailed column, grouped into a price range of 0-50; 50-250; 250-500; 500-750; 750-1000 dollar; and more.</b>

In [17]:
df["price"].values[0]

np.int64(149)

In [18]:
from tqdm import tqdm

In [19]:
%%time
# Seperate by each Price
df["price_group"] = 0
for idx, pri in enumerate(tqdm(df["price"])):
    if df.loc[idx, "price"] < 50:
        df.loc[idx, "price_group"] = 0
    elif 50 <= df.loc[idx, "price"] < 250:
        df.loc[idx, "price_group"] = 1
    elif 250 <= df.loc[idx, "price"] < 500:
        df.loc[idx, "price_group"] = 2
    elif 500 <= df.loc[idx, "price"] < 750:
        df.loc[idx, "price_group"] = 3
    elif 750 <= df.loc[idx, "price"] < 1000:
        df.loc[idx, "price_group"] = 4
    else:
        df.loc[idx, "price_group"] = 5

100%|█████████████████████████████████████████████████████████████████████| 313620/313620 [01:00<00:00, 5176.69it/s]

CPU times: user 1min, sys: 138 ms, total: 1min
Wall time: 1min

In [20]:
# # again, df is a cudf.DataFrame
# s = df["price"]

# # each comparison produces a boolean column; summing them gives the group index
# df["price_group"] = (
#       (s >=   50).astype("int32")
#     + (s >=  250).astype("int32")
#     + (s >=  500).astype("int32")
#     + (s >=  750).astype("int32")
#     + (s >= 1000).astype("int32")
# )

In [21]:
# x = df['price_group'].value_counts().index
# y = df['price_group'].value_counts().values
# plt.figure(figsize=(20,8))
# for i in range(len(x)):
#     height = y[i]
#     plt.text(x[i], height + 0.5, '%.1f' %height, ha='center', va='bottom', size = 12)
# plt.bar(x,y,color = "#FF4457")

## <div style="font-family:Serif;color:#DB3A49; padding:10px; font-size:35px">Price_Breakdown in $1000 dollar$ units from $0-10000 dollar$

In [22]:
# price_range = 0
# fig, axes = plt.subplots(nrows=5, ncols=2, figsize=(18, 22))
# for row in axes:
#     for ax in row:
#         if price_range < 1000:
#             eda_map(df[(df['price'] > price_range*1000) & (df['price'] < (price_range+1)*1000)], 'price',ax)
#             ax.set_title(f"Price Range ${price_range*1000} - ${(price_range+1)*1000} Total Amount: {len(df[(df['price'] > price_range*1000) & (df['price'] < (price_range+1)*1000)])}")
#             price_range += 1
# plt.tight_layout()

<div style="font-family:Serif;background-color:#FFD5E1; padding:30px; font-size:17px"><b>As the boxplot graph we see, Most of the Bnb services are in 0~1000 dollar.</b>

<a id="1"></a>
# <div style="padding:20px;color:white;margin:0;font-size:35px;font-family:Serif;text-align:left;display:fill;border-radius:5px;background-color:#FF4455;overflow:hidden"><b>⭕Suburb _ Each Suburb price in Newyork</b></div>

<div style="font-family:Serif;background-color:#FFD5E1; padding:30px; font-size:17px"><b>There are 5 type of suburb in New York City. Different regions may form different price ranges through regional characteristics. Among them, there may be several factors such as the amount of services and the environment present in an area. In this part, we would like to conduct an analysis on what price ranges are formed in each region and how many services are in progress.</b>

In [23]:
# fig, axes = plt.subplots(nrows=3, ncols=2, figsize=(22, 20))

# # Flatten the 2D array of subplots
# axes = axes.flatten()
# # Loop over each city and its corresponding axis
# for i, city in enumerate(nyc_sub):
#     ax = axes[i]
#     eda_map(df[df['neighbourhood_group'] == city], 'price',ax)
#     ax.set_title(f"{city} - amount: {len(df[df['neighbourhood_group'] == city])} - aver price: {round(np.mean(df[df['neighbourhood_group'] == city]['price']),3)}")

# plt.tight_layout()

## <div style="font-family:Serif;color:#DB3A49; padding:10px; font-size:35px">Analyze each place's room to room distance.

<div style="font-family:Serif;background-color:#FFD5E1; padding:30px; font-size:17px"><b>Manhattan Area:</b> 59.1 square kilometers (22.8 square miles) ==  59100000meter<br><br><b>Brooklyn Area:</b> 183.4 square kilometers (70.8 square miles) == 183400000meter<br><br><b>Queens Area:</b> 464.9 square kilometers (179.2 square miles) == 464900000meter<br><br><b>Bronx Area:</b> 109.0 square kilometers (42.0 square miles) == 109000000meter<br><br><b>Staten Island Area:</b> 151.5 square kilometers (58.5 square miles) == 151500000meter

In [24]:
# suburb_area = [59100000,183400000,464900000,109000000,151500000]
# distance_room_to_room = []
# for i, city in enumerate(nyc_sub):
#     distance_room_to_room.append((suburb_area[i]/len(df[df['neighbourhood_group'] == city]))*(1/1000))

# x = nyc_sub
# y = distance_room_to_room
# plt.figure(figsize=(20,8))
# for i in range(len(x)):
#     height = y[i]
#     plt.text(x[i], height, '%.1f' %height, ha='center', va='bottom', size = 12)
# plt.bar(x,y,color = "#FF4457")

<div style="font-family:Serif;background-color:#FFD5E1; padding:30px; font-size:17px"><b>The density of Airbnb distribution was calculated through the gap between Airbnb services through the number of Airbnb present in each region and the area of the region. From the graph above, we can see that the density of Airbnb services located in Manhattan is the highest density. It means that there is one service every 4.4 square kilometers, and 'staten island' shows that there is more than one Airbnb service every 450~ square kilometers.</b>

<a id="1"></a>
# <div style="padding:20px;color:white;margin:0;font-size:35px;font-family:Serif;text-align:left;display:fill;border-radius:5px;background-color:#FF4455;overflow:hidden"><b>⭕Price_Main bnb service in 50~250 dollars</b></div>

<div style="font-family:Serif;background-color:#FFD5E1; padding:30px; font-size:17px"><b> Accommodations priced between <mark>50 and 250</mark> dollar were the most popular among people. Therefore, the number of accommodations at a specific price range in each region is compared and analyzed with the average price of accommodation.

In [25]:
# fig, axes = plt.subplots(nrows=3, ncols=2, figsize=(22, 20))
# axes = axes.flatten()
# aver_price = []
# # Loop over each city and its corresponding axis
# for i, city in enumerate(nyc_sub):
#     ax = axes[i]
#     req = df[(df['neighbourhood_group'] == city)&(df['price']>50)&(df['price']<250)]
#     eda_map(req, 'price',ax)
#     ax.set_title(f"{city} - amount: {len(req)} - aver price: {round(np.mean(req['price']),3)}")
#     aver_price.append(round(np.mean(req['price']),3))
# plt.tight_layout();

In [26]:
total_amount_sub = []
total_amount_sub_50_250 = []
aver_price_total = []
aver_price_50_250 = []
for i, city in enumerate(nyc_sub):
    req = df[
        (df["neighbourhood_group"] == city) & (df["price"] > 50) & (df["price"] < 250)
    ]
    total_amount_sub.append(len(df[df["neighbourhood_group"] == city]))
    total_amount_sub_50_250.append(len(req))
    aver_price_total.append(
        round(np.mean(df[df["neighbourhood_group"] == city]["price"]), 3)
    )
    aver_price_50_250.append(round(np.mean(req["price"]), 3))

In [27]:
# total_amount_sub_df = pd.DataFrame({'total_amount_sub' : total_amount_sub, 'total_amount_sub_50_250' : total_amount_sub_50_250},index=nyc_sub)
# aver_price_df = pd.DataFrame({'aver_price_total' : aver_price_total, 'aver_price_50_250' : aver_price_50_250},index=nyc_sub)

# fig, ax = plt.subplots(figsize=(20,8))
# bar_width = 0.25

# index = np.arange(5)

# b1 = plt.bar(index, total_amount_sub_df['total_amount_sub'], bar_width, alpha=0.4, color='red', label='total amount')
# b2 = plt.bar(index + bar_width, total_amount_sub_df['total_amount_sub_50_250'], bar_width, alpha=0.4, color='blue', label='total amount _ price range in 50-250')

# plt.xticks(index,nyc_sub)
# plt.title("Compare Total amount of Airbnb and its price range(50,250)")
# plt.xlabel('Suburb', size = 13)
# plt.ylabel('Amount', size = 13)
# plt.legend()
# plt.show()

<div style="font-family:Serif;background-color:#FFD5E1; padding:30px; font-size:17px"> <b>The graph shows that many Airbnb services are widely distributed in the 50-250 price range. In particular, it can be seen that most Airbnb located in Bronx and Staten Island exist in the corresponding price range.</b>

In [28]:
# fig, ax = plt.subplots(figsize=(20,8))
# bar_width = 0.25

# index = np.arange(5)

# b1 = plt.bar(index, aver_price_df['aver_price_total'], bar_width, alpha=0.4, color='red', label='total average price')
# b2 = plt.bar(index + bar_width, aver_price_df['aver_price_50_250'], bar_width, alpha=0.4, color='blue', label='total average price _ price in 50-250')

# plt.xticks(index,nyc_sub)
# plt.title("Compare Total average price of Airbnb and its price range(50,250)")
# plt.xlabel('Suburb', size = 13)
# plt.ylabel('Average Price', size = 13)
# plt.legend()
# plt.show()

<div style="font-family:Serif;background-color:#FFD5E1; padding:30px; font-size:17px"><b>The average price of 50-250 units in each region and the average price of the total price were similar. However, the overall average price in Manhattan is quite different from the average price in the 50-250 range. It can be inferred that this reason is that there is a large amount of Airbnb in Manhattan and a high price range based on the results derived above. On the other hand, it can be seen that the average price of the total Airbnb of "bronx" is lower than the average price of the total Airbnb in the range of 50-250 dollars. In other words, it can be seen that the Airbnb of 'bronx' is formed at a relatively low price.</b>

<a id="1"></a>
# <div style="padding:20px;color:white;margin:0;font-size:35px;font-family:Serif;text-align:left;display:fill;border-radius:5px;background-color:#FF4455;overflow:hidden"><b>⭕Neighbourhood</b></div>

<div style="font-family:Serif;background-color:#FFD5E1; padding:30px; font-size:17px"><b>Data from neighboring areas also exist in the data. It provides conditions for more detailed and detailed understanding and analysis of specific areas of each region through neighboring regions. In this part, we will analyze the average room price of each neighboring area, and compare and analyze the high and low-priced areas compared to the average price of all neighboring areas.</b>

In [29]:
nei_x = []
nei_y = []
colors = []

for nei in df["neighbourhood"].value_counts().index:
    nei_x.append(nei)
    nei_y.append(np.mean(df[df["neighbourhood"] == nei]["price"].values))
# plt.figure(figsize=(20,10))
# plt.hlines(np.mean(nei_y),0,len(nei_x), color='#FF4457', linestyle='solid', linewidth=3)
# plt.text(0, np.mean(nei_y), f'average price per room: {round(np.mean(nei_y),3)}$', ha='right', va='center', color='red')
# for i in range(len(nei_x)):
#     height = nei_y[i]
#     if height > round(np.mean(nei_y),3):
#         plt.text(nei_x[i], height + 0.5, '%.1f' %height, ha='center', va='bottom', size = 12)

for neigh in nei_x:
    if df[df["neighbourhood"] == neigh]["neighbourhood_group"].values[0] == "Manhattan":
        colors.append("red")
    elif (
        df[df["neighbourhood"] == neigh]["neighbourhood_group"].values[0] == "Brooklyn"
    ):
        colors.append("blue")
    elif df[df["neighbourhood"] == neigh]["neighbourhood_group"].values[0] == "Queens":
        colors.append("green")
    elif df[df["neighbourhood"] == neigh]["neighbourhood_group"].values[0] == "Bronx":
        colors.append("orange")
    elif (
        df[df["neighbourhood"] == neigh]["neighbourhood_group"].values[0]
        == "Staten Island"
    ):
        colors.append("purple")

# bars = plt.bar(nei_x,nei_y,color=colors)
# # Create a list of Patch objects that represent the bars in the chart
# color_labels = {'red': 'Manhattan', 'green': 'Brooklyn', 'blue': 'Queens', 'orange': 'Bronx', 'purple': 'Staten Island'}
# patches = [mpatches.Patch(color=color, label=label) for color, label in color_labels.items()]
# # Add the legend with colored labels
# plt.legend(handles=patches)
# plt.show()

In [30]:
nei_x_aver_h = []
nei_x_aver_l = []
nei_y_aver_h = []
nei_y_aver_l = []
for nei in df["neighbourhood"].value_counts().index:
    if np.mean(df[df["neighbourhood"] == nei]["price"].values) >= round(
        np.mean(nei_y), 3
    ):
        nei_x_aver_h.append(nei)
        nei_y_aver_h.append(np.mean(df[df["neighbourhood"] == nei]["price"].values))
    elif np.mean(df[df["neighbourhood"] == nei]["price"].values) < round(
        np.mean(nei_y), 3
    ):
        nei_x_aver_l.append(nei)
        nei_y_aver_l.append(np.mean(df[df["neighbourhood"] == nei]["price"].values))

## <div style="font-family:Serif;color:#DB3A49; padding:10px; font-size:35px">Higher than Average _ Neighborhood

In [31]:
# plt.figure(figsize=(20,8))
# for i in range(len(nei_x_aver_h)):
#     height = nei_y_aver_h[i]
#     plt.text(nei_x_aver_h[i], height + 0.5, '%.1f' %height, ha='center', va='bottom', size = 12)
colors = []
for neigh in nei_x_aver_h:
    if df[df["neighbourhood"] == neigh]["neighbourhood_group"].values[0] == "Manhattan":
        colors.append("red")
    elif (
        df[df["neighbourhood"] == neigh]["neighbourhood_group"].values[0] == "Brooklyn"
    ):
        colors.append("blue")
    elif df[df["neighbourhood"] == neigh]["neighbourhood_group"].values[0] == "Queens":
        colors.append("green")
    elif df[df["neighbourhood"] == neigh]["neighbourhood_group"].values[0] == "Bronx":
        colors.append("orange")
    elif (
        df[df["neighbourhood"] == neigh]["neighbourhood_group"].values[0]
        == "Staten Island"
    ):
        colors.append("purple")
# bars = plt.bar(nei_x_aver_h,nei_y_aver_h,color=colors)
# # Create a list of Patch objects that represent the bars in the chart
# color_labels = {'red': 'Manhattan', 'green': 'Brooklyn', 'blue': 'Queens', 'orange': 'Bronx', 'purple': 'Staten Island'}
# patches = [mpatches.Patch(color=color, label=label) for color, label in color_labels.items()]
# # Add the legend with colored labels
# plt.legend(handles=patches)
# plt.show()

## <div style="font-family:Serif;color:#DB3A49; padding:10px; font-size:35px">Lower than Average _ Neighborhood

In [32]:
# plt.figure(figsize=(20,8))
# for i in range(len(nei_x_aver_l)):
#     height = nei_y_aver_l[i]
#     plt.text(nei_x_aver_l[i], height + 0.5, '%.1f' %height, ha='center', va='bottom', size = 12)
# colors = []
for neigh in nei_x_aver_h:
    if df[df["neighbourhood"] == neigh]["neighbourhood_group"].values[0] == "Manhattan":
        colors.append("red")
    elif (
        df[df["neighbourhood"] == neigh]["neighbourhood_group"].values[0] == "Brooklyn"
    ):
        colors.append("blue")
    elif df[df["neighbourhood"] == neigh]["neighbourhood_group"].values[0] == "Queens":
        colors.append("green")
    elif df[df["neighbourhood"] == neigh]["neighbourhood_group"].values[0] == "Bronx":
        colors.append("orange")
    elif (
        df[df["neighbourhood"] == neigh]["neighbourhood_group"].values[0]
        == "Staten Island"
    ):
        colors.append("purple")
# bars = plt.bar(nei_x_aver_l,nei_y_aver_l,color=colors)
# # Create a list of Patch objects that represent the bars in the chart
# color_labels = {'red': 'Manhattan', 'green': 'Brooklyn', 'blue': 'Queens', 'orange': 'Bronx', 'purple': 'Staten Island'}
# patches = [mpatches.Patch(color=color, label=label) for color, label in color_labels.items()]
# # Add the legend with colored labels
# plt.legend(handles=patches)
# plt.ylim(40,135)
# plt.show()

# Reviews

<a id="1"></a>
# <div style="padding:20px;color:white;margin:0;font-size:35px;font-family:Serif;text-align:left;display:fill;border-radius:5px;background-color:#FF4455;overflow:hidden"><b>⭕ Reviews</b></div>

<div style="font-family:Serif;color:#DB3A49; padding:10px; font-size:35px"> number_of_reviews

<div style="font-family:Serif;background-color:#FFD5E1; padding:30px; font-size:17px"><b> The user's review in the use of accommodation is also a factor that greatly affects the demand and price of accommodation use. In this part, we will analyze how it affects the price of accommodation through the amount of reviews of accommodation users, and analyze various other factors.</b>

In [33]:
y = [
    len(
        df[df["number_of_reviews"] < np.mean(df["number_of_reviews"].values)][
            "number_of_reviews"
        ]
    ),
    len(
        df[df["number_of_reviews"] > np.mean(df["number_of_reviews"].values)][
            "number_of_reviews"
        ]
    ),
]
x = [
    f"Number of places with less reviews than average reviews: \n{len(df[df['number_of_reviews'] < np.mean(df['number_of_reviews'].values)]['number_of_reviews'])}",
    f"Number of places with more reviews than average reviews: \n{len(df[df['number_of_reviews'] > np.mean(df['number_of_reviews'].values)]['number_of_reviews'])}",
]
y_per = [y[0] / len(df), y[1] / len(df)]
explode = [0, 0.1]
# plt.title(f"mean of reviews: {np.mean(df['number_of_reviews'].values)}")
# plt.pie(y_per,labels = x,autopct='%.1f%%',explode = explode,shadow=True);

<div style="font-family:Serif;background-color:#FFD5E1; padding:30px; font-size:17px"><b> It can be seen that the Airbnb service, which has more reviews than the average reviews, has significantly less reviews than the average reviews.</b>

In [34]:
# nor_list = [np.mean(df[df['number_of_reviews']<np.mean(df['number_of_reviews'].values)]['price']),
#       np.mean(df[df['number_of_reviews']>np.mean(df['number_of_reviews'].values)]['price'])]
# plt.figure(figsize=(15,4))
# x = ["less reviews than average reviews","more reviews than average reviews"]
# y = nor_list
# for i in range(len(x)):
#     height = y[i]
#     plt.text(x[i], height + 0.5, '%.1f' %height, ha='center', va='bottom', size = 12)
# plt.bar(x,y,width=0.3,color = "#FF4457")
# plt.ylim(130,180)

<div style="font-family:Serif;background-color:#FFD5E1; padding:30px; font-size:17px">There could be several reasons why Airbnb listings with fewer reviews have higher average prices:<br><br><b>New or recently renovated properties:</b> Listings with fewer reviews may be newer or recently renovated properties that have not had enough time to accumulate many reviews. These properties may have more modern amenities or features that justify higher prices.<br><br><b>Higher-end properties:</b> Listings with fewer reviews may be higher-end properties that attract guests who are willing to pay a premium for luxury or exclusive experiences. These properties may offer unique features or amenities that are not commonly found in other listings.<br><br><b>Limited availability:</b> Listings with fewer reviews may have limited availability due to high demand or limited capacity. This scarcity can drive up prices as guests are willing to pay more for the listing.<br><br><b>Higher guest satisfaction:</b> Listings with fewer reviews may have a higher satisfaction rate among guests, leading to higher prices. Guests may be willing to pay more for a listing that has a high rating and positive reviews.<br><br><b>Strategic pricing:</b> Hosts may price their listings higher if they have fewer reviews to create a perception of exclusivity or desirability. This can lead to higher prices for these listings, even if they do not have significantly better features or amenities.

## <div style="font-family:Serif;color:#DB3A49; padding:10px; font-size:35px">reviews_per_month

In [35]:
# plt.figure(figsize=(20,15))
# ax = plt.gca()
# eda_map(df[df["reviews_per_month"]<15],'reviews_per_month',ax)

<a id="1"></a>
# <div style="padding:20px;color:white;margin:0;font-size:35px;font-family:Serif;text-align:left;display:fill;border-radius:5px;background-color:#FF4455;overflow:hidden"><b>⭕ Calculated_Host_Listings_Count</b></div>

In [36]:
# x = df['calculated_host_listings_count'].value_counts().sort_index().index.astype(str)
# y = df['calculated_host_listings_count'].value_counts().sort_index().values
# plt.figure(figsize=(20,8))
# plt.xlabel("host_listings_count")
# plt.ylabel("amount of host_listings_count")
# plt.plot(x,y,color = "#FF4457")

In [37]:
# plt.figure(figsize=(20,15))
# ax = plt.gca()
# eda_map(df[df["calculated_host_listings_count"]>=1],'calculated_host_listings_count',ax)

<a id="1"></a>
# <div style="padding:20px;color:white;margin:0;font-size:35px;font-family:Serif;text-align:left;display:fill;border-radius:5px;background-color:#FF4455;overflow:hidden"><b>⭕availability_365</b></div>

<div style="font-family:Serif;background-color:#FFD5E1; padding:30px; font-size:17px"><b>The availability date of accommodation also plays an important role in determining the use of accommodation by users in Airbnb services. The more available the accommodation is, the more the owner is affected by the management and profits of the use, and from the user's point of view, various factors such as post-use reviews and price considerations can be considered.</b>

<div style="font-family:Serif;background-color:#FFD5E1; padding:30px; font-size:17px"><b>At first,  visualized on whether there were accommodations available <mark>365 days</mark>, that is, throughout the year, where they were distributed a lot, and the price.</b>

In [38]:
# plt.figure(figsize=(20,15))
# ax = plt.gca()
# plt.title(f"availability - 365days days, total amount: {len(df[df['availability_365']==365])}, average price: {round(np.mean(df[df['availability_365']==365]['price']),3)}")
# eda_map(df[df['availability_365']==365],'price',ax)

In [39]:
# plt.figure(figsize=(20,8))
# plt.boxplot(df[df['availability_365']==365]['price']);

<div style="font-family:Serif;background-color:#FFD5E1; padding:30px; font-size:17px"><b>Only 1,295 accommodations, or about 4% of the total data 31362, were operated 365 days. Figures show that very few Airbnb accommodations operate for 365 days.Also, the average price was higher than expected. Perhaps the outlier was present in the data, which resulted in this result, and as expected, as a result of drawing a boxplot with accommodation facilities that can be booked throughout the year as a basic condition, the outlier existed in excess of a large range. It is not necessary to remove it because it existed in a state that meets all conditions, but it can be confirmed from the boxplot that most of the price range is still maintained at 50-250 dollars. <br><br>Next Step,there are 249days working day in a year. So Check out how much airbnb services are exist can booking days upper than 249 days and its average price.</b>

In [40]:
# plt.figure(figsize=(20,15))
# ax = plt.gca()
# plt.title(f"availability more than 249 days, total amount: {len(df[df['availability_365']>=249])}, average price: {round(np.mean(df[df['availability_365']>=249]['price']),3)}")
# eda_map(df[df['availability_365']>=249],'price',ax)

In [41]:
e = time.time()
print(e - s)

92.76896953582764

<div style="font-family:Serif;background-color:#FFD5E1; padding:30px; font-size:17px"><b>As the date of operation is lowered a little, it can be seen that the total number of accommodations has increased significantly. Airbnb is not a company or business that specializes in operating accommodation, but an individual provides accommodation. It is a predictable result, considering that it is difficult to run every day throughout the year. In addition, the average price has decreased significantly.</b>

#### <div style='text-align:center; font-family:arial'> 🙇🏻‍♂️Thanks For Watching!<br></div><b>