In [1]:
import sys
import os

sys.path.insert(0, os.path.abspath("/home/ElasticNotebook"))
%load_ext ElasticNotebook
from elastic.core.common.pandas import compare_df
import pickle
import cudf

Enabled rmm statistics

In [2]:
%load_ext cudf.pandas

/opt/conda/envs/rapids-25.02/lib/python3.10/site-packages/cudf/pandas/__init__.py:65: UserWarning: cudf.pandas detected an already configured memory resource, ignoring 'CUDF_PANDAS_RMM_MODE'=managed_pool
  warnings.warn(

In [3]:
%LoadCheckpoint /home/dias-benchmarks/notebooks/aieducation/what-course-are-you-going-to-take/src/annotated/checkpoints/pre_cell_29.pickle

[[<elastic.core.graph.variable_snapshot.VariableSnapshot object at 0x7fe3aecc7100>], [<elastic.core.graph.variable_snapshot.VariableSnapshot object at 0x7fe4c5183fd0>], [<elastic.core.graph.variable_snapshot.VariableSnapshot object at 0x7fe3aecc7790>], [<elastic.core.graph.variable_snapshot.VariableSnapshot object at 0x7fe3aecc7580>], [<elastic.core.graph.variable_snapshot.VariableSnapshot object at 0x7fe4c5182ef0>], [<elastic.core.graph.variable_snapshot.VariableSnapshot object at 0x7fe3aecc7670>], [<elastic.core.graph.variable_snapshot.VariableSnapshot object at 0x7fe3aeaf8100>], [<elastic.core.graph.variable_snapshot.VariableSnapshot object at 0x7fe3aeaf85b0>], [<elastic.core.graph.variable_snapshot.VariableSnapshot object at 0x7fe4c5181960>], [<elastic.core.graph.variable_snapshot.VariableSnapshot object at 0x7fe4c5181360>], [<elastic.core.graph.variable_snapshot.VariableSnapshot object at 0x7fe3aecc7910>]]
trying: ['extract_filter_features']
me:  11
trying: ['sns']
me:  0
trying: ['course']
me:  24
trying: ['course_gp']
me:  20
trying: ['np']
me:  0
trying: ['i_2']
me:  22
trying: ['i_1']
me:  14
trying: ['factor']
me:  2
trying: ['pd']
me:  0
trying: ['plt']
me:  0
trying: ['extract_features_from_dataframe']
me:  27
Declaring variable sns
Declaring variable np
Declaring variable pd
Declaring variable plt
Declaring variable factor
Declaring variable extract_filter_features
Declaring variable i_1
Declaring variable course_gp
Declaring variable i_2
Declaring variable course
Declaring variable extract_features_from_dataframe

me:  24
trying: ['course_gp']
me:  20
trying: ['np']
me:  0
trying: ['i_2']
me:  22
trying: ['i_1']
me:  14
trying: ['factor']
me:  2
trying: ['pd']
me:  0
trying: ['plt']
me:  0
trying: ['extract_features_from_dataframe']
me:  27
Declaring variable sns
Declaring variable np
Declaring variable pd
Declaring variable plt
Declaring variable factor
Declaring variable extract_filter_features
Declaring variable i_1
Declaring variable course_gp
Declaring variable i_2
Declaring variable course
Declaring variable extract_features_from_dataframe

In [4]:
%%RecordEvent
%%time
### cell 29 ###

# cell 29
# Use a GPU‐accelerated sort by assigning the result back rather than using inplace
course = course.sort_values("course_rating_mean", ascending=False)

CPU times: user 131 ms, sys: 22.1 ms, total: 154 ms
Wall time: 236 ms

In [5]:
course_opt = course
%LoadCheckpoint /home/dias-benchmarks/notebooks/aieducation/what-course-are-you-going-to-take/src/annotated/checkpoints/post_cell_29.pickle

[[<elastic.core.graph.variable_snapshot.VariableSnapshot object at 0x7fe3aeaf8850>], [<elastic.core.graph.variable_snapshot.VariableSnapshot object at 0x7fe3b0747be0>], [<elastic.core.graph.variable_snapshot.VariableSnapshot object at 0x7fe3aeb27f70>], [<elastic.core.graph.variable_snapshot.VariableSnapshot object at 0x7fe3aeb27af0>], [<elastic.core.graph.variable_snapshot.VariableSnapshot object at 0x7fe3aeb4c700>], [<elastic.core.graph.variable_snapshot.VariableSnapshot object at 0x7fe3aeb4cd90>], [<elastic.core.graph.variable_snapshot.VariableSnapshot object at 0x7fe3b0747b20>], [<elastic.core.graph.variable_snapshot.VariableSnapshot object at 0x7fe3aeb27580>], [<elastic.core.graph.variable_snapshot.VariableSnapshot object at 0x7fe3aeb27d90>], [<elastic.core.graph.variable_snapshot.VariableSnapshot object at 0x7fe3b0747c40>], [<elastic.core.graph.variable_snapshot.VariableSnapshot object at 0x7fe3aeb4cbb0>], [<elastic.core.graph.variable_snapshot.VariableSnapshot object at 0x7fe3aeb27a00>]]
trying: ['np']
me:  0
trying: ['sns']
me:  0
trying: ['course']
me:  30
trying: ['i_2']
me:  22
trying: ['i_1']
me:  14
trying: ['orig_output']
me:  31
trying: ['plt']
me:  0
trying: ['extract_filter_features']
me:  11
trying: ['extract_features_from_dataframe']
me:  27
trying: ['pd']
me:  0
trying: ['factor']
me:  2
trying: ['course_gp']
me:  20
Declaring variable np
Declaring variable sns
Declaring variable plt
Declaring variable pd
Declaring variable factor
Declaring variable extract_filter_features
Declaring variable i_1
Declaring variable course_gp
Declaring variable i_2
Declaring variable extract_features_from_dataframe
Declaring variable course
Declaring variable orig_output

In [21]:
course_opt.tail(10)

,course_unit,course_code,num_ratings,useful,easy,liked,num_reviews,course_rating_int,course_num,course_rating_mean
3019742,WKRPT,WKRPT 400,103,8,44,5,16,0.0,400,0.037037037037037035
3019743,WKRPT,WKRPT 400,103,8,44,5,16,0.0,400,0.037037037037037035
3019744,WKRPT,WKRPT 400,103,8,44,5,16,0.0,400,0.037037037037037035
3019745,WKRPT,WKRPT 400,103,8,44,5,16,0.0,400,0.037037037037037035
3019746,WKRPT,WKRPT 400,103,8,44,5,16,0.0,400,0.037037037037037035
3019747,WKRPT,WKRPT 400,103,8,44,5,16,0.0,400,0.037037037037037035
3019748,WKRPT,WKRPT 400,103,8,44,5,16,0.0,400,0.037037037037037035
3019749,WKRPT,WKRPT 400,103,8,44,5,16,0.0,400,0.037037037037037035
3019750,WKRPT,WKRPT 400,103,8,44,5,16,0.0,400,0.037037037037037035
3019751,WKRPT,WKRPT 400,103,8,44,5,16,0.0,400,0.037037037037037035

In [22]:
course.tail(10)

,course_unit,course_code,num_ratings,useful,easy,liked,num_reviews,course_rating_int,course_num,course_rating_mean
1858815,WKRPT,WKRPT 200,224,14,30,5,13,1.0,200,0.037037037037037035
319638,WKRPT,WKRPT 400,103,8,44,5,16,0.0,400,0.037037037037037035
319639,WKRPT,WKRPT 400,103,8,44,5,16,0.0,400,0.037037037037037035
319640,WKRPT,WKRPT 400,103,8,44,5,16,0.0,400,0.037037037037037035
319641,WKRPT,WKRPT 400,103,8,44,5,16,0.0,400,0.037037037037037035
319642,WKRPT,WKRPT 400,103,8,44,5,16,0.0,400,0.037037037037037035
319643,WKRPT,WKRPT 400,103,8,44,5,16,0.0,400,0.037037037037037035
319644,WKRPT,WKRPT 400,103,8,44,5,16,0.0,400,0.037037037037037035
319645,WKRPT,WKRPT 400,103,8,44,5,16,0.0,400,0.037037037037037035
1878974,WKRPT,WKRPT 200,224,14,30,5,13,0.0,200,0.037037037037037035

In [ ]:
%Checkpoint /home/dias-benchmarks/notebooks/aieducation/what-course-are-you-going-to-take/src/rewritten/cell_29/checkpoints/post_cell_29_try_0.pickle

In [ ]:
%PrintCellInfo opt_cell_exec_info

In [ ]:
with open(
    "/home/dias-benchmarks/notebooks/aieducation/what-course-are-you-going-to-take/src/opt_cell_exec_info_29_try_0.pkl",
    "wb",
) as f:
    pickle.dump(opt_cell_exec_info[29], f)

In [ ]:
opt_output = Out.get(4)

In [ ]:
assert compare_df(course_opt, course)

import numpy as np
from elastic.core.common.pandas import is_type_styler

is_orig_output_pd = isinstance(orig_output, (pd.Series, pd.DataFrame, pd.Index))
is_opt_output_pd = isinstance(opt_output, (pd.Series, pd.DataFrame, pd.Index))
is_orig_output_array = isinstance(
    orig_output, (cudf.pandas._wrappers.numpy.ndarray, np.ndarray)
)
is_opt_output_array = isinstance(
    opt_output, (cudf.pandas._wrappers.numpy.ndarray, np.ndarray)
)
is_orig_output_styler = is_type_styler(type(orig_output))
is_opt_output_styler = is_type_styler(type(opt_output))
if is_orig_output_styler and is_opt_output_styler:
    assert orig_output.to_html() == opt_output.to_html()
elif is_orig_output_styler:
    assert orig_output.to_html() == opt_output.to_html()
elif is_opt_output_styler:
    assert opt_output.to_html() == orig_output

if is_orig_output_pd and is_opt_output_pd:
    assert orig_output.equals(opt_output)
# TODO(jie): this is a hack.
elif (
    (is_orig_output_pd or is_opt_output_pd)
    and (is_orig_output_array or is_opt_output_array)
) or (is_orig_output_array and is_opt_output_array):
    assert list(orig_output) == list(opt_output)
else:
    assert orig_output == opt_output

ValueError: Content of df1 and df2 do not match