In [1]:
# %load_ext cudf.pandas

In [2]:
# %load_ext cudf.pandas
# Import Visualization FrameWork Tools
import pandas as pd
import numpy as np

# import matplotlib.pyplot as plt
# import seaborn as sns
# # import missingno as msno
# import matplotlib.pyplot as plt
# from PIL import Image
# import matplotlib.patches as mpatches
import time

In [3]:
start_time = time.time()

In [4]:
### cell 0 ###

df = pd.read_csv("/home/dias-benchmarks/new_notebooks/nyc-airbnb/AB_NYC_2019.csv")
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [5]:
### cell 1 ###

df.shape

(48895, 16)

In [6]:
### cell 2 ###

factor = 10
df = pd.concat([df] * factor)

In [7]:
### cell 3 ###

# check null-value and each columns' dtype to do EDA.
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 488950 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              488950 non-null  int64
 1   name                            488790 non-null  object
 2   host_id                         488950 non-null  int64
 3   host_name                       488740 non-null  object
 4   neighbourhood_group             488950 non-null  object
 5   neighbourhood                   488950 non-null  object
 6   latitude                        488950 non-null  float64
 7   longitude                       488950 non-null  float64
 8   room_type                       488950 non-null  object
 9   price                           488950 non-null  int64
 10  minimum_nights                  488950 non-null  int64
 11  number_of_reviews               488950 non-null  int64
 12  last_review                     388430 non-null  object
 13  reviews_per_month               388430 non-null  float64
 14  calculated_host_listings_count  488950 non-null  int64
 15  availability_365                488950 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 63.4+ MB
None

In [8]:
### cell 4 ###

df = df.drop(["id", "last_review", "name", "host_name"], axis=1)
df.head()

,host_id,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
0,2787,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,0.21,6,365
1,2845,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,0.38,2,355
2,4632,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,1,365
3,4869,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,4.64,1,194
4,7192,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,0.10,1,0

In [9]:
### cell 5 ###

df = df.drop(df[df["availability_365"] == 0].index, axis=0)
df = df.reset_index()
df.head()

,index,host_id,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
0,0,2787,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,0.21,6,365
1,1,2845,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,0.38,2,355
2,2,4632,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,1,365
3,3,4869,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,4.64,1,194
4,5,7322,Manhattan,Murray Hill,40.74767,-73.97500,Entire home/apt,200,3,74,0.59,1,129

In [10]:
### cell 6 ###

df["reviews_per_month"] = df["reviews_per_month"].fillna(0)
df.head()

,index,host_id,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
0,0,2787,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,0.21,6,365
1,1,2845,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,0.38,2,355
2,2,4632,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,0.00,1,365
3,3,4869,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,4.64,1,194
4,5,7322,Manhattan,Murray Hill,40.74767,-73.97500,Entire home/apt,200,3,74,0.59,1,129

In [11]:
### cell 7 ###

df.isnull().sum()

index                             0
host_id                           0
neighbourhood_group               0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
dtype: int64

In [12]:
### cell 8 ###

df.shape

(313620, 13)

In [13]:
# def eda_map(df,feature, ax):
#     plt.figure(figsize=(15,15))
#     image = Image.open("/kaggle/input/new-york-city-airbnb-open-data/New_York_City_.png") # Load the image
#     df.plot(kind='scatter', x='longitude', y='latitude', label='AirBnB On service', c=str(feature), ax=ax, # Create the scatter plot
#             cmap=plt.get_cmap('jet'), colorbar=True, alpha=0.4, zorder=5, s=1)
#     ax.imshow(image,extent=[-74.258, -73.7, 40.49,40.92]) # Set the extent of the image

In [14]:
# plt.figure(figsize=(20,15))
# ax = plt.gca()
# eda_map(df,'price',ax)

In [15]:
### cell 9 ###

nyc_sub_1 = ["Manhattan", "Brooklyn", "Queens", "Bronx", "Staten Island"]

x_1 = nyc_sub_1
y_1 = []
for i_1 in x_1:
    y_1.append(df[df["neighbourhood_group"] == i_1]["price"].values.tolist())
y_1

[[225,
  150,
  200,
  79,
  150,
  135,
  85,
  85,
  140,
  190,
  150,
  44,
  180,
  50,
  52,
  50,
  40,
  68,
  135,
  150,
  151,
  200,
  110,
  69,
  180,
  375,
  250,
  52,
  80,
  99,
  225,
  230,
  51,
  65,
  190,
  200,
  150,
  110,
  285,
  94,
  60,
  140,
  89,
  98,
  60,
  65,
  500,
  100,
  59,
  140,
  350,
  199,
  235,
  225,
  170,
  170,
  150,
  85,
  120,
  185,
  105,
  130,
  115,
  195,
  156,
  69,
  225,
  219,
  99,
  250,
  125,
  170,
  165,
  150,
  99,
  75,
  275,
  299,
  83,
  123,
  105,
  200,
  121,
  100,
  130,
  199,
  130,
  64,
  250,
  239,
  305,
  155,
  60,
  120,
  150,
  250,
  500,
  225,
  125,
  92,
  175,
  99,
  140,
  500,
  120,
  110,
  130,
  175,
  205,
  390,
  75,
  90,
  68,
  115,
  129,
  75,
  212,
  95,
  135,
  124,
  122,
  109,
  85,
  195,
  575,
  150,
  90,
  65,
  500,
  250,
  125,
  200,
  113,
  250,
  150,
  150,
  71,
  169,
  139,
  95,
  150,
  125,
  130,
  67,
  212,
  249,
  60,
  120,
  169,
  225,
  85,
  211,
  65,
  99,
  290,
  110,
  395,
  189,
  122,
  130,
  185,
  175,
  259,
  295,
  165,
  95,
  55,
  300,
  175,
  75,
  200,
  295,
  198,
  99,
  140,
  75,
  250,
  75,
  205,
  185,
  190,
  250,
  175,
  65,
  170,
  115,
  89,
  49,
  400,
  100,
  189,
  120,
  300,
  199,
  120,
  199,
  100,
  99,
  255,
  169,
  110,
  150,
  89,
  50,
  149,
  68,
  75,
  160,
  95,
  150,
  80,
  230,
  300,
  80,
  199,
  199,
  100,
  55,
  146,
  150,
  199,
  69,
  300,
  288,
  225,
  110,
  130,
  89,
  135,
  90,
  270,
  145,
  179,
  110,
  325,
  130,
  190,
  200,
  195,
  241,
  399,
  200,
  71,
  226,
  154,
  700,
  125,
  125,
  400,
  850,
  140,
  115,
  185,
  495,
  760,
  325,
  189,
  101,
  153,
  80,
  300,
  155,
  225,
  85,
  310,
  109,
  167,
  195,
  99,
  130,
  350,
  250,
  125,
  300,
  150,
  56,
  299,
  1300,
  99,
  110,
  85,
  139,
  50,
  250,
  300,
  130,
  180,
  240,
  385,
  165,
  219,
  139,
  209,
  90,
  199,
  300,
  250,
  140,
  90,
  295,
  150,
  99,
  75,
  75,
  109,
  86,
  99,
  89,
  199,
  110,
  135,
  115,
  499,
  109,
  219,
  159,
  106,
  299,
  179,
  250,
  87,
  75,
  80,
  125,
  95,
  121,
  350,
  75,
  95,
  89,
  195,
  189,
  265,
  129,
  199,
  110,
  135,
  175,
  3000,
  549,
  200,
  160,
  180,
  105,
  74,
  165,
  99,
  104,
  225,
  100,
  135,
  125,
  85,
  200,
  90,
  300,
  125,
  125,
  145,
  225,
  269,
  100,
  225,
  275,
  160,
  125,
  99,
  325,
  99,
  325,
  275,
  145,
  151,
  208,
  110,
  58,
  395,
  90,
  100,
  94,
  250,
  225,
  99,
  239,
  50,
  174,
  75,
  129,
  311,
  100,
  210,
  89,
  89,
  99,
  85,
  80,
  135,
  125,
  80,
  328,
  99,
  165,
  150,
  499,
  220,
  79,
  99,
  130,
  150,
  104,
  72,
  150,
  185,
  200,
  82,
  90,
  115,
  170,
  118,
  135,
  50,
  265,
  90,
  220,
  93,
  165,
  295,
  300,
  225,
  102,
  195,
  170,
  185,
  195,
  79,
  500,
  210,
  300,
  220,
  120,
  295,
  125,
  190,
  76,
  107,
  151,
  79,
  120,
  700,
  96,
  75,
  120,
  215,
  200,
  199,
  75,
  125,
  229,
  165,
  55,
  55,
  275,
  331,
  60,
  179,
  249,
  120,
  120,
  199,
  125,
  80,
  130,
  90,
  150,
  50,
  136,
  165,
  80,
  1000,
  225,
  165,
  200,
  700,
  65,
  263,
  60,
  433,
  79,
  250,
  145,
  234,
  65,
  135,
  595,
  109,
  90,
  100,
  85,
  87,
  95,
  349,
  160,
  149,
  150,
  79,
  197,
  127,
  110,
  99,
  113,
  295,
  2000,
  200,
  108,
  141,
  88,
  65,
  167,
  125,
  95,
  92,
  179,
  55,
  129,
  134,
  250,
  95,
  165,
  105,
  73,
  75,
  55,
  95,
  72,
  250,
  230,
  900,
  399,
  299,
  100,
  175,
  240,
  495,
  79,
  150,
  144,
  195,
  169,
  95,
  375,
  80,
  100,
  200,
  65,
  155,
  249,
  75,
  171,
  185,
  120,
  133,
  259,
  97,
  199,
  125,
  125,
  170,
  199,
  80,
  155,
  120,
  179,
  99,
  200,
  400,
  500,
  95,
  80,
  133,
  155,
  600,
  50,
  65,
  100,
  165,
  120,
  85,
  59,
  280,
  140,
  200,
  225,
  189,
  69,
  160,
  220,
  85,
  225,
  210,
  140,
  250,
  159,
  210,
  225,
  75,
  105,
  150,
  130,
  115,
  116,
  85,
  465,
  195,
  36,
  85,
  95,
  165,
  99,
  225,
  81,
  340,
  135,
  100,
  290,
  148,
  60,
  60,
  45,
  60,
  60,
  121,
  179,
  80,
  65,
  69,
  135,
  120,
  69,
  65,
  130,
  130,
  79,
  40,
  99,
  240,
  235,
  80,
  400,
  349,
  495,
  999,
  109,
  175,
  150,
  80,
  145,
  300,
  131,
  160,
  65,
  235,
  195,
  120,
  100,
  166,
  99,
  195,
  100,
  62,
  90,
  88,
  125,
  200,
  100,
  125,
  150,
  125,
  90,
  65,
  100,
  113,
  108,
  165,
  110,
  339,
  500,
  49,
  2500,
  175,
  100,
  170,
  150,
  49,
  49,
  170,
  105,
  100,
  160,
  145,
  180,
  225,
  250,
  125,
  399,
  75,
  190,
  200,
  199,
  140,
  124,
  295,
  160,
  230,
  118,
  85,
  55,
  140,
  179,
  200,
  100,
  50,
  235,
  125,
  250,
  650,
  100,
  195,
  75,
  100,
  190,
  100,
  159,
  91,
  200,
  169,
  249,
  199,
  88,
  170,
  135,
  165,
  170,
  349,
  65,
  420,
  97,
  191,
  187,
  172,
  950,
  99,
  334,
  130,
  575,
  300,
  56,
  191,
  135,
  75,
  99,
  550,
  105,
  165,
  499,
  60,
  95,
  275,
  130,
  100,
  1000,
  499,
  45,
  195,
  190,
  95,
  350,
  80,
  120,
  42,
  425,
  150,
  199,
  110,
  120,
  145,
  100,
  50,
  70,
  58,
  131,
  250,
  185,
  300,
  176,
  40,
  75,
  85,
  175,
  240,
  160,
  250,
  650,
  158,
  85,
  209,
  89,
  45,
  70,
  125,
  140,
  47,
  115,
  199,
  110,
  133,
  79,
  200,
  175,
  135,
  90,
  115,
  110,
  109,
  1000,
  750,
  47,
  48,
  129,
  170,
  94,
  108,
  89,
  89,
  239,
  80,
  125,
  100,
  1000,
  225,
  275,
  80,
  70,
  44,
  125,
  130,
  130,
  125,
  199,
  248,
  85,
  79,
  150,
  285,
  190,
  90,
  125,
  148,
  120,
  200,
  55,
  175,
  240,
  95,
  41,
  135,
  290,
  100,
  200,
  135,
  72,
  58,
  250,
  95,
  125,
  300,
  350,
  95,
  595,
  165,
  269,
  350,
  80,
  150,
  219,
  119,
  140,
  110,
  140,
  94,
  50,
  145,
  145,
  109,
  150,
  399,
  465,
  235,
  82,
  82,
  145,
  95,
  350,
  250,
  93,
  93,
  199,
  125,
  169,
  61,
  190,
  185,
  85,
  75,
  280,
  210,
  199,
  219,
  220,
  120,
  105,
  265,
  54,
  800,
  99,
  120,
  169,
  180,
  111,
  90,
  89,
  217,
  350,
  160,
  260,
  200,
  200,
  285,
  120,
  120,
  210,
  95,
  99,
  100,
  99,
  160,
  65,
  125,
  112,
  232,
  140,
  5000,
  220,
  178,
  55,
  300,
  175,
  169,
  60,
  150,
  99,
  73,
  179,
  300,
  299,
  98,
  96,
  125,
  100,
  80,
  100,
  220,
  159,
  299,
  1100,
  140,
  138,
  69,
  269,
  150,
  121,
  89,
  135,
  175,
  156,
  104,
  80,
  550,
  199,
  100,
  125,
  99,
  350,
  125,
  155,
  250,
  300,
  120,
  240,
  72,
  100,
  ...],
 [149,
  89,
  89,
  140,
  215,
  99,
  130,
  80,
  110,
  120,
  60,
  55,
  70,
  89,
  35,
  85,
  150,
  120,
  120,
  150,
  110,
  80,
  80,
  228,
  144,
  150,
  49,
  80,
  200,
  55,
  275,
  105,
  95,
  145,
  130,
  800,
  105,
  85,
  65,
  131,
  98,
  250,
  105,
  125,
  175,
  101,
  220,
  125,
  80,
  200,
  125,
  120,
  325,
  99,
  400,
  75,
  90,
  70,
  89,
  77,
  76,
  125,
  135,
  250,
  199,
  115,
  160,
  195,
  80,
  44,
  85,
  125,
  115,
  125,
  475,
  69,
  135,
  250,
  70,
  165,
  50,
  150,
  110,
  200,
  150,
  90,
  120,
  175,
  135,
  249,
  100,
  140,
  71,
  69,
  195,
  159,
  135,
  135,
  65,
  99,
  285,
  59,
  39,
  135,
  70,
  60,
  100,
  70,
  60,
  75,
  130,
  95,
  175,
  190,
  49,
  140,
  150,
  190,
  135,
  145,
  250,
  125,
  70,
  229,
  59,
  195,
  169,
  69,
  169,
  179,
  350,
  120,
  349,
  349,
  165,
  249,
  200,
  185,
  65,
  130,
  199,
  179,
  79,
  650,
  90,
  120,
  100,
  175,
  120,
  200,
  165,
  123,
  130,
  190,
  599,
  100,
  135,
  175,
  165,
  95,
  55,
  199,
  80,
  150,
  110,
  190,
  200,
  165,
  99,
  39,
  260,
  165,
  225,
  50,
  170,
  250,
  141,
  64,
  249,
  120,
  495,
  250,
  451,
  150,
  125,
  255,
  72,
  165,
  165,
  75,
  139,
  88,
  80,
  450,
  130,
  46,
  60,
  105,
  85,
  85,
  91,
  97,
  179,
  500,
  70,
  99,
  350,
  170,
  169,
  99,
  160,
  215,
  130,
  65,
  43,
  42,
  85,
  139,
  105,
  99,
  100,
  190,
  248,
  100,
  145,
  41,
  120,
  195,
  70,
  145,
  185,
  40,
  79,
  100,
  110,
  172,
  116,
  120,
  150,
  79,
  130,
  239,
  220,
  80,
  135,
  100,
  80,
  110,
  180,
  350,
  85,
  55,
  438,
  110,
  279,
  280,
  199,
  180,
  85,
  199,
  100,
  129,
  96,
  199,
  199,
  199,
  69,
  199,
  199,
  199,
  199,
  199,
  349,
  249,
  299,
  179,
  599,
  220,
  89,
  170,
  98,
  125,
  48,
  64,
  139,
  130,
  92,
  145,
  99,
  110,
  147,
  60,
  50,
  45,
  34,
  190,
  75,
  93,
  60,
  60,
  60,
  110,
  135,
  165,
  127,
  402,
  75,
  800,
  100,
  90,
  97,
  91,
  125,
  300,
  100,
  65,
  110,
  100,
  140,
  120,
  175,
  275,
  250,
  120,
  50,
  157,
  199,
  199,
  199,
  199,
  199,
  135,
  199,
  75,
  70,
  130,
  75,
  100,
  130,
  75,
  180,
  65,
  149,
  75,
  225,
  100,
  135,
  89,
  120,
  59,
  49,
  79,
  185,
  95,
  75,
  180,
  165,
  79,
  115,
  115,
  120,
  178,
  145,
  125,
  77,
  92,
  65,
  72,
  120,
  94,
  129,
  85,
  125,
  159,
  45,
  90,
  250,
  90,
  298,
  123,
  88,
  145,
  75,
  229,
  300,
  75,
  120,
  160,
  125,
  119,
  500,
  87,
  160,
  90,
  250,
  130,
  55,
  125,
  150,
  70,
  138,
  200,
  105,
  150,
  55,
  299,
  189,
  90,
  80,
  39,
  55,
  142,
  70,
  55,
  229,
  200,
  250,
  235,
  100,
  55,
  165,
  110,
  82,
  450,
  145,
  225,
  100,
  55,
  142,
  300,
  105,
  125,
  226,
  50,
  200,
  102,
  220,
  385,
  160,
  249,
  80,
  120,
  169,
  85,
  90,
  46,
  325,
  175,
  209,
  68,
  49,
  349,
  800,
  349,
  125,
  350,
  150,
  180,
  99,
  90,
  250,
  89,
  375,
  200,
  36,
  275,
  80,
  280,
  90,
  189,
  200,
  69,
  90,
  135,
  199,
  65,
  185,
  152,
  250,
  80,
  110,
  115,
  180,
  95,
  60,
  133,
  120,
  80,
  50,
  155,
  150,
  115,
  195,
  175,
  80,
  275,
  72,
  250,
  54,
  129,
  500,
  149,
  180,
  100,
  128,
  65,
  300,
  115,
  275,
  198,
  35,
  250,
  64,
  65,
  400,
  125,
  120,
  119,
  60,
  80,
  110,
  120,
  120,
  350,
  73,
  150,
  195,
  200,
  72,
  75,
  100,
  139,
  100,
  199,
  140,
  45,
  109,
  42,
  355,
  80,
  89,
  35,
  249,
  220,
  198,
  155,
  550,
  60,
  380,
  84,
  68,
  150,
  85,
  78,
  220,
  150,
  80,
  150,
  150,
  70,
  100,
  69,
  330,
  210,
  175,
  85,
  65,
  146,
  120,
  85,
  168,
  50,
  129,
  199,
  199,
  99,
  70,
  66,
  95,
  52,
  195,
  50,
  73,
  100,
  39,
  125,
  220,
  61,
  125,
  105,
  100,
  50,
  103,
  70,
  55,
  82,
  52,
  115,
  175,
  100,
  45,
  165,
  312,
  200,
  230,
  200,
  150,
  75,
  145,
  149,
  100,
  45,
  145,
  195,
  199,
  82,
  150,
  128,
  40,
  200,
  115,
  250,
  85,
  79,
  160,
  79,
  215,
  49,
  190,
  68,
  185,
  109,
  125,
  75,
  89,
  99,
  90,
  42,
  155,
  100,
  51,
  4000,
  60,
  70,
  70,
  200,
  68,
  55,
  96,
  150,
  85,
  80,
  800,
  130,
  36,
  140,
  75,
  69,
  100,
  75,
  100,
  85,
  145,
  55,
  289,
  149,
  150,
  44,
  60,
  74,
  62,
  249,
  240,
  149,
  170,
  68,
  50,
  65,
  200,
  65,
  185,
  115,
  140,
  62,
  95,
  62,
  95,
  60,
  80,
  50,
  79,
  140,
  191,
  139,
  120,
  295,
  120,
  107,
  98,
  110,
  165,
  160,
  38,
  50,
  890,
  51,
  150,
  56,
  70,
  70,
  157,
  145,
  280,
  220,
  35,
  30,
  98,
  125,
  195,
  99,
  85,
  75,
  53,
  150,
  135,
  100,
  50,
  400,
  97,
  189,
  49,
  120,
  89,
  62,
  130,
  64,
  150,
  98,
  70,
  325,
  149,
  130,
  65,
  100,
  225,
  100,
  275,
  145,
  120,
  50,
  195,
  350,
  40,
  225,
  225,
  200,
  235,
  75,
  249,
  50,
  85,
  78,
  50,
  63,
  55,
  289,
  125,
  150,
  90,
  130,
  70,
  96,
  75,
  195,
  139,
  116,
  60,
  1395,
  225,
  60,
  60,
  83,
  175,
  149,
  125,
  109,
  138,
  80,
  89,
  110,
  72,
  325,
  125,
  195,
  189,
  182,
  105,
  185,
  85,
  550,
  80,
  175,
  95,
  150,
  70,
  95,
  50,
  75,
  60,
  130,
  120,
  99,
  300,
  40,
  100,
  90,
  40,
  300,
  189,
  49,
  140,
  190,
  60,
  105,
  139,
  499,
  79,
  152,
  50,
  212,
  99,
  55,
  35,
  200,
  117,
  99,
  89,
  155,
  80,
  137,
  120,
  95,
  75,
  103,
  150,
  99,
  179,
  105,
  84,
  60,
  220,
  275,
  142,
  225,
  59,
  350,
  75,
  42,
  60,
  125,
  99,
  250,
  135,
  147,
  65,
  350,
  181,
  65,
  155,
  50,
  120,
  55,
  150,
  150,
  240,
  390,
  295,
  160,
  60,
  125,
  115,
  131,
  175,
  299,
  48,
  75,
  55,
  75,
  151,
  199,
  45,
  160,
  36,
  225,
  215,
  65,
  78,
  120,
  90,
  95,
  100,
  188,
  495,
  55,
  150,
  40,
  150,
  65,
  79,
  225,
  100,
  85,
  98,
  262,
  100,
  59,
  100,
  175,
  40,
  140,
  110,
  131,
  53,
  65,
  55,
  67,
  129,
  69,
  250,
  120,
  129,
  199,
  450,
  45,
  70,
  125,
  195,
  58,
  75,
  95,
  275,
  160,
  200,
  45,
  80,
  70,
  72,
  75,
  29,
  175,
  175,
  171,
  99,
  72,
  300,
  100,
  60,
  138,
  100,
  95,
  85,
  129,
  69,
  68,
  69,
  155,
  165,
  120,
  110,
  62,
  104,
  89,
  345,
  149,
  190,
  55,
  275,
  250,
  66,
  65,
  70,
  49,
  47,
  229,
  165,
  68,
  85,
  170,
  95,
  149,
  89,
  115,
  160,
  95,
  99,
  40,
  50,
  55,
  224,
  280,
  ...],
 [130,
  70,
  140,
  79,
  350,
  55,
  98,
  140,
  265,
  140,
  140,
  99,
  115,
  80,
  50,
  70,
  110,
  97,
  129,
  42,
  42,
  33,
  107,
  95,
  75,
  50,
  95,
  55,
  75,
  75,
  79,
  54,
  80,
  96,
  85,
  65,
  55,
  52,
  45,
  75,
  215,
  77,
  75,
  69,
  39,
  70,
  80,
  85,
  107,
  350,
  75,
  69,
  150,
  110,
  55,
  54,
  92,
  69,
  100,
  55,
  99,
  45,
  89,
  61,
  75,
  58,
  100,
  65,
  62,
  120,
  68,
  120,
  120,
  245,
  55,
  39,
  140,
  80,
  390,
  299,
  55,
  250,
  55,
  69,
  70,
  45,
  45,
  60,
  57,
  400,
  63,
  107,
  80,
  60,
  45,
  55,
  81,
  70,
  63,
  77,
  349,
  115,
  99,
  85,
  81,
  78,
  160,
  75,
  130,
  38,
  75,
  69,
  46,
  59,
  200,
  160,
  150,
  70,
  60,
  35,
  73,
  133,
  175,
  65,
  55,
  119,
  69,
  150,
  90,
  84,
  110,
  100,
  80,
  79,
  80,
  145,
  100,
  138,
  70,
  75,
  150,
  35,
  59,
  59,
  349,
  59,
  59,
  250,
  75,
  51,
  188,
  48,
  56,
  59,
  120,
  110,
  79,
  35,
  70,
  200,
  38,
  195,
  100,
  140,
  100,
  95,
  29,
  75,
  110,
  56,
  73,
  45,
  79,
  66,
  130,
  85,
  180,
  150,
  135,
  45,
  75,
  149,
  72,
  325,
  55,
  60,
  99,
  64,
  120,
  47,
  65,
  60,
  100,
  100,
  79,
  120,
  65,
  88,
  86,
  59,
  65,
  275,
  85,
  45,
  100,
  75,
  90,
  63,
  395,
  59,
  95,
  80,
  55,
  60,
  95,
  95,
  400,
  50,
  55,
  55,
  75,
  130,
  65,
  160,
  60,
  69,
  149,
  59,
  60,
  53,
  40,
  70,
  35,
  255,
  70,
  59,
  200,
  119,
  50,
  89,
  70,
  250,
  59,
  99,
  74,
  105,
  89,
  48,
  70,
  39,
  38,
  100,
  125,
  150,
  108,
  184,
  120,
  59,
  95,
  125,
  80,
  95,
  85,
  113,
  75,
  100,
  45,
  100,
  170,
  49,
  39,
  239,
  125,
  145,
  50,
  39,
  79,
  50,
  50,
  120,
  149,
  170,
  95,
  70,
  45,
  65,
  150,
  200,
  65,
  250,
  78,
  200,
  99,
  69,
  58,
  76,
  110,
  180,
  120,
  70,
  65,
  79,
  80,
  47,
  90,
  50,
  80,
  50,
  98,
  96,
  195,
  100,
  89,
  63,
  39,
  39,
  110,
  49,
  150,
  95,
  58,
  190,
  70,
  189,
  97,
  180,
  110,
  50,
  55,
  160,
  149,
  56,
  64,
  90,
  95,
  170,
  40,
  39,
  100,
  65,
  150,
  65,
  105,
  125,
  98,
  100,
  44,
  119,
  150,
  99,
  195,
  105,
  70,
  105,
  150,
  60,
  375,
  107,
  49,
  50,
  70,
  130,
  50,
  90,
  165,
  99,
  45,
  82,
  99,
  95,
  40,
  50,
  119,
  107,
  70,
  80,
  65,
  45,
  99,
  100,
  72,
  89,
  50,
  72,
  34,
  40,
  90,
  80,
  99,
  120,
  110,
  54,
  135,
  38,
  55,
  90,
  47,
  85,
  50,
  50,
  36,
  42,
  300,
  65,
  49,
  65,
  60,
  259,
  134,
  73,
  200,
  38,
  38,
  60,
  160,
  69,
  59,
  58,
  112,
  70,
  60,
  65,
  54,
  100,
  47,
  175,
  47,
  55,
  100,
  50,
  55,
  46,
  58,
  89,
  150,
  150,
  369,
  100,
  145,
  60,
  40,
  80,
  115,
  78,
  275,
  65,
  150,
  153,
  37,
  49,
  75,
  122,
  168,
  105,
  125,
  45,
  155,
  45,
  85,
  120,
  300,
  140,
  150,
  130,
  50,
  225,
  70,
  149,
  200,
  180,
  50,
  290,
  59,
  45,
  44,
  49,
  68,
  160,
  70,
  86,
  75,
  48,
  65,
  39,
  65,
  135,
  300,
  125,
  53,
  60,
  60,
  250,
  150,
  80,
  398,
  130,
  45,
  85,
  109,
  99,
  64,
  59,
  96,
  50,
  158,
  70,
  290,
  85,
  109,
  75,
  80,
  250,
  122,
  65,
  45,
  125,
  59,
  150,
  70,
  150,
  45,
  350,
  99,
  79,
  35,
  125,
  120,
  35,
  75,
  70,
  289,
  90,
  52,
  138,
  58,
  100,
  200,
  60,
  89,
  42,
  52,
  450,
  55,
  87,
  195,
  250,
  100,
  70,
  75,
  75,
  37,
  80,
  135,
  46,
  100,
  75,
  59,
  100,
  125,
  175,
  199,
  120,
  50,
  104,
  65,
  99,
  109,
  89,
  52,
  75,
  55,
  80,
  55,
  70,
  100,
  69,
  50,
  70,
  37,
  120,
  85,
  40,
  59,
  77,
  57,
  55,
  60,
  42,
  50,
  50,
  100,
  187,
  85,
  40,
  75,
  45,
  45,
  50,
  100,
  170,
  99,
  70,
  45,
  55,
  55,
  48,
  50,
  65,
  55,
  100,
  90,
  34,
  50,
  79,
  74,
  47,
  140,
  75,
  125,
  70,
  88,
  58,
  77,
  144,
  89,
  65,
  200,
  49,
  155,
  500,
  65,
  125,
  60,
  114,
  70,
  60,
  103,
  109,
  37,
  150,
  55,
  100,
  89,
  130,
  100,
  89,
  60,
  43,
  59,
  239,
  49,
  65,
  90,
  39,
  65,
  88,
  90,
  70,
  200,
  250,
  375,
  55,
  36,
  26,
  95,
  700,
  55,
  50,
  49,
  70,
  155,
  179,
  47,
  45,
  46,
  37,
  80,
  48,
  45,
  79,
  90,
  62,
  85,
  60,
  45,
  69,
  275,
  100,
  180,
  38,
  40,
  50,
  50,
  65,
  125,
  115,
  49,
  45,
  59,
  55,
  130,
  200,
  60,
  90,
  50,
  145,
  71,
  97,
  140,
  70,
  60,
  55,
  84,
  129,
  50,
  40,
  37,
  1800,
  65,
  118,
  120,
  110,
  90,
  40,
  120,
  40,
  87,
  50,
  40,
  150,
  45,
  90,
  120,
  100,
  55,
  85,
  45,
  95,
  59,
  43,
  86,
  80,
  95,
  45,
  95,
  34,
  150,
  70,
  73,
  219,
  52,
  79,
  225,
  40,
  500,
  175,
  80,
  299,
  350,
  95,
  120,
  750,
  60,
  110,
  225,
  96,
  125,
  50,
  169,
  40,
  40,
  59,
  75,
  215,
  70,
  65,
  60,
  65,
  99,
  86,
  60,
  175,
  119,
  80,
  58,
  60,
  40,
  40,
  50,
  65,
  250,
  135,
  190,
  79,
  289,
  85,
  49,
  125,
  75,
  260,
  60,
  130,
  30,
  60,
  33,
  75,
  200,
  60,
  58,
  58,
  60,
  43,
  100,
  87,
  170,
  45,
  36,
  119,
  89,
  52,
  195,
  70,
  49,
  40,
  151,
  71,
  125,
  38,
  509,
  35,
  95,
  75,
  99,
  75,
  50,
  160,
  65,
  95,
  47,
  45,
  35,
  99,
  100,
  125,
  80,
  200,
  48,
  125,
  99,
  45,
  120,
  38,
  100,
  178,
  70,
  255,
  125,
  150,
  80,
  110,
  65,
  70,
  74,
  174,
  40,
  101,
  40,
  40,
  70,
  200,
  40,
  205,
  90,
  27,
  65,
  40,
  125,
  40,
  69,
  60,
  55,
  50,
  40,
  60,
  40,
  125,
  75,
  75,
  85,
  35,
  40,
  55,
  200,
  50,
  73,
  90,
  87,
  38,
  159,
  115,
  32,
  37,
  70,
  75,
  55,
  90,
  99,
  55,
  2350,
  61,
  38,
  50,
  135,
  85,
  199,
  100,
  150,
  65,
  70,
  69,
  150,
  105,
  450,
  60,
  65,
  32,
  71,
  85,
  79,
  72,
  60,
  90,
  75,
  120,
  35,
  70,
  49,
  75,
  100,
  76,
  115,
  150,
  65,
  59,
  79,
  135,
  120,
  144,
  145,
  88,
  122,
  34,
  99,
  60,
  55,
  200,
  110,
  35,
  130,
  77,
  80,
  199,
  40,
  165,
  75,
  27,
  105,
  55,
  100,
  45,
  300,
  65,
  74,
  40,
  60,
  109,
  98,
  125,
  44,
  30,
  60,
  50,
  75,
  150,
  200,
  117,
  49,
  67,
  249,
  66,
  400,
  95,
  47,
  60,
  27,
  42,
  100,
  140,
  76,
  150,
  ...],
 [40,
  45,
  90,
  105,
  90,
  77,
  37,
  125,
  50,
  50,
  42,
  50,
  120,
  49,
  100,
  35,
  45,
  250,
  39,
  49,
  38,
  60,
  60,
  30,
  85,
  65,
  60,
  90,
  60,
  50,
  45,
  43,
  75,
  120,
  140,
  53,
  65,
  75,
  250,
  32,
  50,
  70,
  80,
  40,
  71,
  55,
  44,
  50,
  95,

In [16]:
### cell 10 ###

nyc_sub_2 = ["Manhattan", "Brooklyn", "Queens", "Bronx", "Staten Island"]
# --- End of sample data creation ---


# The optimized one-liner using groupby
# .apply(list) collects all values for each group into a list
grouped_prices = df.groupby("neighbourhood_group")["price"].apply(list)

# The result is a pandas Series, with boroughs as the index
# and the list of prices as the values.
# print(grouped_prices)
#
# Output would look like:
# neighbourhood_group
# Bronx              [175, 229, 403, 114, 308, 401, 381, 169, 14...
# Brooklyn           [187, 134, 421, 112, 179, 344, 185, 335, 41...
# Manhattan          [376, 269, 396, 429, 332, 287, 237, 275, 43...
# Queens             [487, 310, 342, 290, 488, 303, 442, 334, 16...
# Staten Island      [410, 423, 222, 172, 497, 180, 290, 391, 16...

# To get the exact same output as your original code (a list of lists in a specific order)
# you can reindex the result and convert it to a list.
y_optimized = grouped_prices.reindex(nyc_sub_2).tolist()
y_optimized

[[225,
  150,
  200,
  79,
  150,
  135,
  85,
  85,
  140,
  190,
  150,
  44,
  180,
  50,
  52,
  50,
  40,
  68,
  135,
  150,
  151,
  200,
  110,
  69,
  180,
  375,
  250,
  52,
  80,
  99,
  225,
  230,
  51,
  65,
  190,
  200,
  150,
  110,
  285,
  94,
  60,
  140,
  89,
  98,
  60,
  65,
  500,
  100,
  59,
  140,
  350,
  199,
  235,
  225,
  170,
  170,
  150,
  85,
  120,
  185,
  105,
  130,
  115,
  195,
  156,
  69,
  225,
  219,
  99,
  250,
  125,
  170,
  165,
  150,
  99,
  75,
  275,
  299,
  83,
  123,
  105,
  200,
  121,
  100,
  130,
  199,
  130,
  64,
  250,
  239,
  305,
  155,
  60,
  120,
  150,
  250,
  500,
  225,
  125,
  92,
  175,
  99,
  140,
  500,
  120,
  110,
  130,
  175,
  205,
  390,
  75,
  90,
  68,
  115,
  129,
  75,
  212,
  95,
  135,
  124,
  122,
  109,
  85,
  195,
  575,
  150,
  90,
  65,
  500,
  250,
  125,
  200,
  113,
  250,
  150,
  150,
  71,
  169,
  139,
  95,
  150,
  125,
  130,
  67,
  212,
  249,
  60,
  120,
  169,
  225,
  85,
  211,
  65,
  99,
  290,
  110,
  395,
  189,
  122,
  130,
  185,
  175,
  259,
  295,
  165,
  95,
  55,
  300,
  175,
  75,
  200,
  295,
  198,
  99,
  140,
  75,
  250,
  75,
  205,
  185,
  190,
  250,
  175,
  65,
  170,
  115,
  89,
  49,
  400,
  100,
  189,
  120,
  300,
  199,
  120,
  199,
  100,
  99,
  255,
  169,
  110,
  150,
  89,
  50,
  149,
  68,
  75,
  160,
  95,
  150,
  80,
  230,
  300,
  80,
  199,
  199,
  100,
  55,
  146,
  150,
  199,
  69,
  300,
  288,
  225,
  110,
  130,
  89,
  135,
  90,
  270,
  145,
  179,
  110,
  325,
  130,
  190,
  200,
  195,
  241,
  399,
  200,
  71,
  226,
  154,
  700,
  125,
  125,
  400,
  850,
  140,
  115,
  185,
  495,
  760,
  325,
  189,
  101,
  153,
  80,
  300,
  155,
  225,
  85,
  310,
  109,
  167,
  195,
  99,
  130,
  350,
  250,
  125,
  300,
  150,
  56,
  299,
  1300,
  99,
  110,
  85,
  139,
  50,
  250,
  300,
  130,
  180,
  240,
  385,
  165,
  219,
  139,
  209,
  90,
  199,
  300,
  250,
  140,
  90,
  295,
  150,
  99,
  75,
  75,
  109,
  86,
  99,
  89,
  199,
  110,
  135,
  115,
  499,
  109,
  219,
  159,
  106,
  299,
  179,
  250,
  87,
  75,
  80,
  125,
  95,
  121,
  350,
  75,
  95,
  89,
  195,
  189,
  265,
  129,
  199,
  110,
  135,
  175,
  3000,
  549,
  200,
  160,
  180,
  105,
  74,
  165,
  99,
  104,
  225,
  100,
  135,
  125,
  85,
  200,
  90,
  300,
  125,
  125,
  145,
  225,
  269,
  100,
  225,
  275,
  160,
  125,
  99,
  325,
  99,
  325,
  275,
  145,
  151,
  208,
  110,
  58,
  395,
  90,
  100,
  94,
  250,
  225,
  99,
  239,
  50,
  174,
  75,
  129,
  311,
  100,
  210,
  89,
  89,
  99,
  85,
  80,
  135,
  125,
  80,
  328,
  99,
  165,
  150,
  499,
  220,
  79,
  99,
  130,
  150,
  104,
  72,
  150,
  185,
  200,
  82,
  90,
  115,
  170,
  118,
  135,
  50,
  265,
  90,
  220,
  93,
  165,
  295,
  300,
  225,
  102,
  195,
  170,
  185,
  195,
  79,
  500,
  210,
  300,
  220,
  120,
  295,
  125,
  190,
  76,
  107,
  151,
  79,
  120,
  700,
  96,
  75,
  120,
  215,
  200,
  199,
  75,
  125,
  229,
  165,
  55,
  55,
  275,
  331,
  60,
  179,
  249,
  120,
  120,
  199,
  125,
  80,
  130,
  90,
  150,
  50,
  136,
  165,
  80,
  1000,
  225,
  165,
  200,
  700,
  65,
  263,
  60,
  433,
  79,
  250,
  145,
  234,
  65,
  135,
  595,
  109,
  90,
  100,
  85,
  87,
  95,
  349,
  160,
  149,
  150,
  79,
  197,
  127,
  110,
  99,
  113,
  295,
  2000,
  200,
  108,
  141,
  88,
  65,
  167,
  125,
  95,
  92,
  179,
  55,
  129,
  134,
  250,
  95,
  165,
  105,
  73,
  75,
  55,
  95,
  72,
  250,
  230,
  900,
  399,
  299,
  100,
  175,
  240,
  495,
  79,
  150,
  144,
  195,
  169,
  95,
  375,
  80,
  100,
  200,
  65,
  155,
  249,
  75,
  171,
  185,
  120,
  133,
  259,
  97,
  199,
  125,
  125,
  170,
  199,
  80,
  155,
  120,
  179,
  99,
  200,
  400,
  500,
  95,
  80,
  133,
  155,
  600,
  50,
  65,
  100,
  165,
  120,
  85,
  59,
  280,
  140,
  200,
  225,
  189,
  69,
  160,
  220,
  85,
  225,
  210,
  140,
  250,
  159,
  210,
  225,
  75,
  105,
  150,
  130,
  115,
  116,
  85,
  465,
  195,
  36,
  85,
  95,
  165,
  99,
  225,
  81,
  340,
  135,
  100,
  290,
  148,
  60,
  60,
  45,
  60,
  60,
  121,
  179,
  80,
  65,
  69,
  135,
  120,
  69,
  65,
  130,
  130,
  79,
  40,
  99,
  240,
  235,
  80,
  400,
  349,
  495,
  999,
  109,
  175,
  150,
  80,
  145,
  300,
  131,
  160,
  65,
  235,
  195,
  120,
  100,
  166,
  99,
  195,
  100,
  62,
  90,
  88,
  125,
  200,
  100,
  125,
  150,
  125,
  90,
  65,
  100,
  113,
  108,
  165,
  110,
  339,
  500,
  49,
  2500,
  175,
  100,
  170,
  150,
  49,
  49,
  170,
  105,
  100,
  160,
  145,
  180,
  225,
  250,
  125,
  399,
  75,
  190,
  200,
  199,
  140,
  124,
  295,
  160,
  230,
  118,
  85,
  55,
  140,
  179,
  200,
  100,
  50,
  235,
  125,
  250,
  650,
  100,
  195,
  75,
  100,
  190,
  100,
  159,
  91,
  200,
  169,
  249,
  199,
  88,
  170,
  135,
  165,
  170,
  349,
  65,
  420,
  97,
  191,
  187,
  172,
  950,
  99,
  334,
  130,
  575,
  300,
  56,
  191,
  135,
  75,
  99,
  550,
  105,
  165,
  499,
  60,
  95,
  275,
  130,
  100,
  1000,
  499,
  45,
  195,
  190,
  95,
  350,
  80,
  120,
  42,
  425,
  150,
  199,
  110,
  120,
  145,
  100,
  50,
  70,
  58,
  131,
  250,
  185,
  300,
  176,
  40,
  75,
  85,
  175,
  240,
  160,
  250,
  650,
  158,
  85,
  209,
  89,
  45,
  70,
  125,
  140,
  47,
  115,
  199,
  110,
  133,
  79,
  200,
  175,
  135,
  90,
  115,
  110,
  109,
  1000,
  750,
  47,
  48,
  129,
  170,
  94,
  108,
  89,
  89,
  239,
  80,
  125,
  100,
  1000,
  225,
  275,
  80,
  70,
  44,
  125,
  130,
  130,
  125,
  199,
  248,
  85,
  79,
  150,
  285,
  190,
  90,
  125,
  148,
  120,
  200,
  55,
  175,
  240,
  95,
  41,
  135,
  290,
  100,
  200,
  135,
  72,
  58,
  250,
  95,
  125,
  300,
  350,
  95,
  595,
  165,
  269,
  350,
  80,
  150,
  219,
  119,
  140,
  110,
  140,
  94,
  50,
  145,
  145,
  109,
  150,
  399,
  465,
  235,
  82,
  82,
  145,
  95,
  350,
  250,
  93,
  93,
  199,
  125,
  169,
  61,
  190,
  185,
  85,
  75,
  280,
  210,
  199,
  219,
  220,
  120,
  105,
  265,
  54,
  800,
  99,
  120,
  169,
  180,
  111,
  90,
  89,
  217,
  350,
  160,
  260,
  200,
  200,
  285,
  120,
  120,
  210,
  95,
  99,
  100,
  99,
  160,
  65,
  125,
  112,
  232,
  140,
  5000,
  220,
  178,
  55,
  300,
  175,
  169,
  60,
  150,
  99,
  73,
  179,
  300,
  299,
  98,
  96,
  125,
  100,
  80,
  100,
  220,
  159,
  299,
  1100,
  140,
  138,
  69,
  269,
  150,
  121,
  89,
  135,
  175,
  156,
  104,
  80,
  550,
  199,
  100,
  125,
  99,
  350,
  125,
  155,
  250,
  300,
  120,
  240,
  72,
  100,
  ...],
 [149,
  89,
  89,
  140,
  215,
  99,
  130,
  80,
  110,
  120,
  60,
  55,
  70,
  89,
  35,
  85,
  150,
  120,
  120,
  150,
  110,
  80,
  80,
  228,
  144,
  150,
  49,
  80,
  200,
  55,
  275,
  105,
  95,
  145,
  130,
  800,
  105,
  85,
  65,
  131,
  98,
  250,
  105,
  125,
  175,
  101,
  220,
  125,
  80,
  200,
  125,
  120,
  325,
  99,
  400,
  75,
  90,
  70,
  89,
  77,
  76,
  125,
  135,
  250,
  199,
  115,
  160,
  195,
  80,
  44,
  85,
  125,
  115,
  125,
  475,
  69,
  135,
  250,
  70,
  165,
  50,
  150,
  110,
  200,
  150,
  90,
  120,
  175,
  135,
  249,
  100,
  140,
  71,
  69,
  195,
  159,
  135,
  135,
  65,
  99,
  285,
  59,
  39,
  135,
  70,
  60,
  100,
  70,
  60,
  75,
  130,
  95,
  175,
  190,
  49,
  140,
  150,
  190,
  135,
  145,
  250,
  125,
  70,
  229,
  59,
  195,
  169,
  69,
  169,
  179,
  350,
  120,
  349,
  349,
  165,
  249,
  200,
  185,
  65,
  130,
  199,
  179,
  79,
  650,
  90,
  120,
  100,
  175,
  120,
  200,
  165,
  123,
  130,
  190,
  599,
  100,
  135,
  175,
  165,
  95,
  55,
  199,
  80,
  150,
  110,
  190,
  200,
  165,
  99,
  39,
  260,
  165,
  225,
  50,
  170,
  250,
  141,
  64,
  249,
  120,
  495,
  250,
  451,
  150,
  125,
  255,
  72,
  165,
  165,
  75,
  139,
  88,
  80,
  450,
  130,
  46,
  60,
  105,
  85,
  85,
  91,
  97,
  179,
  500,
  70,
  99,
  350,
  170,
  169,
  99,
  160,
  215,
  130,
  65,
  43,
  42,
  85,
  139,
  105,
  99,
  100,
  190,
  248,
  100,
  145,
  41,
  120,
  195,
  70,
  145,
  185,
  40,
  79,
  100,
  110,
  172,
  116,
  120,
  150,
  79,
  130,
  239,
  220,
  80,
  135,
  100,
  80,
  110,
  180,
  350,
  85,
  55,
  438,
  110,
  279,
  280,
  199,
  180,
  85,
  199,
  100,
  129,
  96,
  199,
  199,
  199,
  69,
  199,
  199,
  199,
  199,
  199,
  349,
  249,
  299,
  179,
  599,
  220,
  89,
  170,
  98,
  125,
  48,
  64,
  139,
  130,
  92,
  145,
  99,
  110,
  147,
  60,
  50,
  45,
  34,
  190,
  75,
  93,
  60,
  60,
  60,
  110,
  135,
  165,
  127,
  402,
  75,
  800,
  100,
  90,
  97,
  91,
  125,
  300,
  100,
  65,
  110,
  100,
  140,
  120,
  175,
  275,
  250,
  120,
  50,
  157,
  199,
  199,
  199,
  199,
  199,
  135,
  199,
  75,
  70,
  130,
  75,
  100,
  130,
  75,
  180,
  65,
  149,
  75,
  225,
  100,
  135,
  89,
  120,
  59,
  49,
  79,
  185,
  95,
  75,
  180,
  165,
  79,
  115,
  115,
  120,
  178,
  145,
  125,
  77,
  92,
  65,
  72,
  120,
  94,
  129,
  85,
  125,
  159,
  45,
  90,
  250,
  90,
  298,
  123,
  88,
  145,
  75,
  229,
  300,
  75,
  120,
  160,
  125,
  119,
  500,
  87,
  160,
  90,
  250,
  130,
  55,
  125,
  150,
  70,
  138,
  200,
  105,
  150,
  55,
  299,
  189,
  90,
  80,
  39,
  55,
  142,
  70,
  55,
  229,
  200,
  250,
  235,
  100,
  55,
  165,
  110,
  82,
  450,
  145,
  225,
  100,
  55,
  142,
  300,
  105,
  125,
  226,
  50,
  200,
  102,
  220,
  385,
  160,
  249,
  80,
  120,
  169,
  85,
  90,
  46,
  325,
  175,
  209,
  68,
  49,
  349,
  800,
  349,
  125,
  350,
  150,
  180,
  99,
  90,
  250,
  89,
  375,
  200,
  36,
  275,
  80,
  280,
  90,
  189,
  200,
  69,
  90,
  135,
  199,
  65,
  185,
  152,
  250,
  80,
  110,
  115,
  180,
  95,
  60,
  133,
  120,
  80,
  50,
  155,
  150,
  115,
  195,
  175,
  80,
  275,
  72,
  250,
  54,
  129,
  500,
  149,
  180,
  100,
  128,
  65,
  300,
  115,
  275,
  198,
  35,
  250,
  64,
  65,
  400,
  125,
  120,
  119,
  60,
  80,
  110,
  120,
  120,
  350,
  73,
  150,
  195,
  200,
  72,
  75,
  100,
  139,
  100,
  199,
  140,
  45,
  109,
  42,
  355,
  80,
  89,
  35,
  249,
  220,
  198,
  155,
  550,
  60,
  380,
  84,
  68,
  150,
  85,
  78,
  220,
  150,
  80,
  150,
  150,
  70,
  100,
  69,
  330,
  210,
  175,
  85,
  65,
  146,
  120,
  85,
  168,
  50,
  129,
  199,
  199,
  99,
  70,
  66,
  95,
  52,
  195,
  50,
  73,
  100,
  39,
  125,
  220,
  61,
  125,
  105,
  100,
  50,
  103,
  70,
  55,
  82,
  52,
  115,
  175,
  100,
  45,
  165,
  312,
  200,
  230,
  200,
  150,
  75,
  145,
  149,
  100,
  45,
  145,
  195,
  199,
  82,
  150,
  128,
  40,
  200,
  115,
  250,
  85,
  79,
  160,
  79,
  215,
  49,
  190,
  68,
  185,
  109,
  125,
  75,
  89,
  99,
  90,
  42,
  155,
  100,
  51,
  4000,
  60,
  70,
  70,
  200,
  68,
  55,
  96,
  150,
  85,
  80,
  800,
  130,
  36,
  140,
  75,
  69,
  100,
  75,
  100,
  85,
  145,
  55,
  289,
  149,
  150,
  44,
  60,
  74,
  62,
  249,
  240,
  149,
  170,
  68,
  50,
  65,
  200,
  65,
  185,
  115,
  140,
  62,
  95,
  62,
  95,
  60,
  80,
  50,
  79,
  140,
  191,
  139,
  120,
  295,
  120,
  107,
  98,
  110,
  165,
  160,
  38,
  50,
  890,
  51,
  150,
  56,
  70,
  70,
  157,
  145,
  280,
  220,
  35,
  30,
  98,
  125,
  195,
  99,
  85,
  75,
  53,
  150,
  135,
  100,
  50,
  400,
  97,
  189,
  49,
  120,
  89,
  62,
  130,
  64,
  150,
  98,
  70,
  325,
  149,
  130,
  65,
  100,
  225,
  100,
  275,
  145,
  120,
  50,
  195,
  350,
  40,
  225,
  225,
  200,
  235,
  75,
  249,
  50,
  85,
  78,
  50,
  63,
  55,
  289,
  125,
  150,
  90,
  130,
  70,
  96,
  75,
  195,
  139,
  116,
  60,
  1395,
  225,
  60,
  60,
  83,
  175,
  149,
  125,
  109,
  138,
  80,
  89,
  110,
  72,
  325,
  125,
  195,
  189,
  182,
  105,
  185,
  85,
  550,
  80,
  175,
  95,
  150,
  70,
  95,
  50,
  75,
  60,
  130,
  120,
  99,
  300,
  40,
  100,
  90,
  40,
  300,
  189,
  49,
  140,
  190,
  60,
  105,
  139,
  499,
  79,
  152,
  50,
  212,
  99,
  55,
  35,
  200,
  117,
  99,
  89,
  155,
  80,
  137,
  120,
  95,
  75,
  103,
  150,
  99,
  179,
  105,
  84,
  60,
  220,
  275,
  142,
  225,
  59,
  350,
  75,
  42,
  60,
  125,
  99,
  250,
  135,
  147,
  65,
  350,
  181,
  65,
  155,
  50,
  120,
  55,
  150,
  150,
  240,
  390,
  295,
  160,
  60,
  125,
  115,
  131,
  175,
  299,
  48,
  75,
  55,
  75,
  151,
  199,
  45,
  160,
  36,
  225,
  215,
  65,
  78,
  120,
  90,
  95,
  100,
  188,
  495,
  55,
  150,
  40,
  150,
  65,
  79,
  225,
  100,
  85,
  98,
  262,
  100,
  59,
  100,
  175,
  40,
  140,
  110,
  131,
  53,
  65,
  55,
  67,
  129,
  69,
  250,
  120,
  129,
  199,
  450,
  45,
  70,
  125,
  195,
  58,
  75,
  95,
  275,
  160,
  200,
  45,
  80,
  70,
  72,
  75,
  29,
  175,
  175,
  171,
  99,
  72,
  300,
  100,
  60,
  138,
  100,
  95,
  85,
  129,
  69,
  68,
  69,
  155,
  165,
  120,
  110,
  62,
  104,
  89,
  345,
  149,
  190,
  55,
  275,
  250,
  66,
  65,
  70,
  49,
  47,
  229,
  165,
  68,
  85,
  170,
  95,
  149,
  89,
  115,
  160,
  95,
  99,
  40,
  50,
  55,
  224,
  280,
  ...],
 [130,
  70,
  140,
  79,
  350,
  55,
  98,
  140,
  265,
  140,
  140,
  99,
  115,
  80,
  50,
  70,
  110,
  97,
  129,
  42,
  42,
  33,
  107,
  95,
  75,
  50,
  95,
  55,
  75,
  75,
  79,
  54,
  80,
  96,
  85,
  65,
  55,
  52,
  45,
  75,
  215,
  77,
  75,
  69,
  39,
  70,
  80,
  85,
  107,
  350,
  75,
  69,
  150,
  110,
  55,
  54,
  92,
  69,
  100,
  55,
  99,
  45,
  89,
  61,
  75,
  58,
  100,
  65,
  62,
  120,
  68,
  120,
  120,
  245,
  55,
  39,
  140,
  80,
  390,
  299,
  55,
  250,
  55,
  69,
  70,
  45,
  45,
  60,
  57,
  400,
  63,
  107,
  80,
  60,
  45,
  55,
  81,
  70,
  63,
  77,
  349,
  115,
  99,
  85,
  81,
  78,
  160,
  75,
  130,
  38,
  75,
  69,
  46,
  59,
  200,
  160,
  150,
  70,
  60,
  35,
  73,
  133,
  175,
  65,
  55,
  119,
  69,
  150,
  90,
  84,
  110,
  100,
  80,
  79,
  80,
  145,
  100,
  138,
  70,
  75,
  150,
  35,
  59,
  59,
  349,
  59,
  59,
  250,
  75,
  51,
  188,
  48,
  56,
  59,
  120,
  110,
  79,
  35,
  70,
  200,
  38,
  195,
  100,
  140,
  100,
  95,
  29,
  75,
  110,
  56,
  73,
  45,
  79,
  66,
  130,
  85,
  180,
  150,
  135,
  45,
  75,
  149,
  72,
  325,
  55,
  60,
  99,
  64,
  120,
  47,
  65,
  60,
  100,
  100,
  79,
  120,
  65,
  88,
  86,
  59,
  65,
  275,
  85,
  45,
  100,
  75,
  90,
  63,
  395,
  59,
  95,
  80,
  55,
  60,
  95,
  95,
  400,
  50,
  55,
  55,
  75,
  130,
  65,
  160,
  60,
  69,
  149,
  59,
  60,
  53,
  40,
  70,
  35,
  255,
  70,
  59,
  200,
  119,
  50,
  89,
  70,
  250,
  59,
  99,
  74,
  105,
  89,
  48,
  70,
  39,
  38,
  100,
  125,
  150,
  108,
  184,
  120,
  59,
  95,
  125,
  80,
  95,
  85,
  113,
  75,
  100,
  45,
  100,
  170,
  49,
  39,
  239,
  125,
  145,
  50,
  39,
  79,
  50,
  50,
  120,
  149,
  170,
  95,
  70,
  45,
  65,
  150,
  200,
  65,
  250,
  78,
  200,
  99,
  69,
  58,
  76,
  110,
  180,
  120,
  70,
  65,
  79,
  80,
  47,
  90,
  50,
  80,
  50,
  98,
  96,
  195,
  100,
  89,
  63,
  39,
  39,
  110,
  49,
  150,
  95,
  58,
  190,
  70,
  189,
  97,
  180,
  110,
  50,
  55,
  160,
  149,
  56,
  64,
  90,
  95,
  170,
  40,
  39,
  100,
  65,
  150,
  65,
  105,
  125,
  98,
  100,
  44,
  119,
  150,
  99,
  195,
  105,
  70,
  105,
  150,
  60,
  375,
  107,
  49,
  50,
  70,
  130,
  50,
  90,
  165,
  99,
  45,
  82,
  99,
  95,
  40,
  50,
  119,
  107,
  70,
  80,
  65,
  45,
  99,
  100,
  72,
  89,
  50,
  72,
  34,
  40,
  90,
  80,
  99,
  120,
  110,
  54,
  135,
  38,
  55,
  90,
  47,
  85,
  50,
  50,
  36,
  42,
  300,
  65,
  49,
  65,
  60,
  259,
  134,
  73,
  200,
  38,
  38,
  60,
  160,
  69,
  59,
  58,
  112,
  70,
  60,
  65,
  54,
  100,
  47,
  175,
  47,
  55,
  100,
  50,
  55,
  46,
  58,
  89,
  150,
  150,
  369,
  100,
  145,
  60,
  40,
  80,
  115,
  78,
  275,
  65,
  150,
  153,
  37,
  49,
  75,
  122,
  168,
  105,
  125,
  45,
  155,
  45,
  85,
  120,
  300,
  140,
  150,
  130,
  50,
  225,
  70,
  149,
  200,
  180,
  50,
  290,
  59,
  45,
  44,
  49,
  68,
  160,
  70,
  86,
  75,
  48,
  65,
  39,
  65,
  135,
  300,
  125,
  53,
  60,
  60,
  250,
  150,
  80,
  398,
  130,
  45,
  85,
  109,
  99,
  64,
  59,
  96,
  50,
  158,
  70,
  290,
  85,
  109,
  75,
  80,
  250,
  122,
  65,
  45,
  125,
  59,
  150,
  70,
  150,
  45,
  350,
  99,
  79,
  35,
  125,
  120,
  35,
  75,
  70,
  289,
  90,
  52,
  138,
  58,
  100,
  200,
  60,
  89,
  42,
  52,
  450,
  55,
  87,
  195,
  250,
  100,
  70,
  75,
  75,
  37,
  80,
  135,
  46,
  100,
  75,
  59,
  100,
  125,
  175,
  199,
  120,
  50,
  104,
  65,
  99,
  109,
  89,
  52,
  75,
  55,
  80,
  55,
  70,
  100,
  69,
  50,
  70,
  37,
  120,
  85,
  40,
  59,
  77,
  57,
  55,
  60,
  42,
  50,
  50,
  100,
  187,
  85,
  40,
  75,
  45,
  45,
  50,
  100,
  170,
  99,
  70,
  45,
  55,
  55,
  48,
  50,
  65,
  55,
  100,
  90,
  34,
  50,
  79,
  74,
  47,
  140,
  75,
  125,
  70,
  88,
  58,
  77,
  144,
  89,
  65,
  200,
  49,
  155,
  500,
  65,
  125,
  60,
  114,
  70,
  60,
  103,
  109,
  37,
  150,
  55,
  100,
  89,
  130,
  100,
  89,
  60,
  43,
  59,
  239,
  49,
  65,
  90,
  39,
  65,
  88,
  90,
  70,
  200,
  250,
  375,
  55,
  36,
  26,
  95,
  700,
  55,
  50,
  49,
  70,
  155,
  179,
  47,
  45,
  46,
  37,
  80,
  48,
  45,
  79,
  90,
  62,
  85,
  60,
  45,
  69,
  275,
  100,
  180,
  38,
  40,
  50,
  50,
  65,
  125,
  115,
  49,
  45,
  59,
  55,
  130,
  200,
  60,
  90,
  50,
  145,
  71,
  97,
  140,
  70,
  60,
  55,
  84,
  129,
  50,
  40,
  37,
  1800,
  65,
  118,
  120,
  110,
  90,
  40,
  120,
  40,
  87,
  50,
  40,
  150,
  45,
  90,
  120,
  100,
  55,
  85,
  45,
  95,
  59,
  43,
  86,
  80,
  95,
  45,
  95,
  34,
  150,
  70,
  73,
  219,
  52,
  79,
  225,
  40,
  500,
  175,
  80,
  299,
  350,
  95,
  120,
  750,
  60,
  110,
  225,
  96,
  125,
  50,
  169,
  40,
  40,
  59,
  75,
  215,
  70,
  65,
  60,
  65,
  99,
  86,
  60,
  175,
  119,
  80,
  58,
  60,
  40,
  40,
  50,
  65,
  250,
  135,
  190,
  79,
  289,
  85,
  49,
  125,
  75,
  260,
  60,
  130,
  30,
  60,
  33,
  75,
  200,
  60,
  58,
  58,
  60,
  43,
  100,
  87,
  170,
  45,
  36,
  119,
  89,
  52,
  195,
  70,
  49,
  40,
  151,
  71,
  125,
  38,
  509,
  35,
  95,
  75,
  99,
  75,
  50,
  160,
  65,
  95,
  47,
  45,
  35,
  99,
  100,
  125,
  80,
  200,
  48,
  125,
  99,
  45,
  120,
  38,
  100,
  178,
  70,
  255,
  125,
  150,
  80,
  110,
  65,
  70,
  74,
  174,
  40,
  101,
  40,
  40,
  70,
  200,
  40,
  205,
  90,
  27,
  65,
  40,
  125,
  40,
  69,
  60,
  55,
  50,
  40,
  60,
  40,
  125,
  75,
  75,
  85,
  35,
  40,
  55,
  200,
  50,
  73,
  90,
  87,
  38,
  159,
  115,
  32,
  37,
  70,
  75,
  55,
  90,
  99,
  55,
  2350,
  61,
  38,
  50,
  135,
  85,
  199,
  100,
  150,
  65,
  70,
  69,
  150,
  105,
  450,
  60,
  65,
  32,
  71,
  85,
  79,
  72,
  60,
  90,
  75,
  120,
  35,
  70,
  49,
  75,
  100,
  76,
  115,
  150,
  65,
  59,
  79,
  135,
  120,
  144,
  145,
  88,
  122,
  34,
  99,
  60,
  55,
  200,
  110,
  35,
  130,
  77,
  80,
  199,
  40,
  165,
  75,
  27,
  105,
  55,
  100,
  45,
  300,
  65,
  74,
  40,
  60,
  109,
  98,
  125,
  44,
  30,
  60,
  50,
  75,
  150,
  200,
  117,
  49,
  67,
  249,
  66,
  400,
  95,
  47,
  60,
  27,
  42,
  100,
  140,
  76,
  150,
  ...],
 [40,
  45,
  90,
  105,
  90,
  77,
  37,
  125,
  50,
  50,
  42,
  50,
  120,
  49,
  100,
  35,
  45,
  250,
  39,
  49,
  38,
  60,
  60,
  30,
  85,
  65,
  60,
  90,
  60,
  50,
  45,
  43,
  75,
  120,
  140,
  53,
  65,
  75,
  250,
  32,
  50,
  70,
  80,
  40,
  71,
  55,
  44,
  50,
  95,

In [17]:
### cell 11 ###

df["price"].values[0]

149

In [18]:
### cell 12 ###

# Seperate by each Price
df["price_group"] = 0
for idx, pri in enumerate(df["price"]):
    if df.loc[idx, "price"] < 50:
        df.loc[idx, "price_group"] = 0
    elif 50 <= df.loc[idx, "price"] < 250:
        df.loc[idx, "price_group"] = 1
    elif 250 <= df.loc[idx, "price"] < 500:
        df.loc[idx, "price_group"] = 2
    elif 500 <= df.loc[idx, "price"] < 750:
        df.loc[idx, "price_group"] = 3
    elif 750 <= df.loc[idx, "price"] < 1000:
        df.loc[idx, "price_group"] = 4
    else:
        df.loc[idx, "price_group"] = 5

In [19]:
### cell 13 ###

suburb_area = [59100000, 183400000, 464900000, 109000000, 151500000]
distance_room_to_room = []
for i_2, city_1 in enumerate(nyc_sub_2):
    distance_room_to_room.append(
        (suburb_area[i_2] / len(df[df["neighbourhood_group"] == city_1])) * (1 / 1000)
    )

distance_room_to_room

[0.43587285198023457,
 1.495921696574225,
 10.816658911121452,
 11.925601750547047,
 45.770392749244714]

In [20]:
### cell 14 ###

total_amount_sub = []
total_amount_sub_50_250 = []
aver_price_total = []
aver_price_50_250 = []
for i_3, city_2 in enumerate(nyc_sub_2):
    req = df[
        (df["neighbourhood_group"] == city_2) & (df["price"] > 50) & (df["price"] < 250)
    ]
    total_amount_sub.append(len(df[df["neighbourhood_group"] == city_2]))
    total_amount_sub_50_250.append(len(req))
    aver_price_total.append(
        round(np.mean(df[df["neighbourhood_group"] == city_2]["price"]), 3)
    )
    aver_price_50_250.append(round(np.mean(req["price"]), 3))
total_amount_sub, total_amount_sub_50_250, aver_price_total, aver_price_50_250

([135590, 122600, 42980, 9140, 3310],
 [98450, 92400, 29720, 5730, 2250],
 [214.202, 132.852, 100.03, 89.008, 114.23],
 [137.576, 113.951, 99.322, 92.529, 99.213])

In [21]:
### cell 15 ###

nei_x_1 = []
nei_y_1 = []
colors_1 = []

for nei_1 in df["neighbourhood"].value_counts().index:
    nei_x_1.append(nei_1)
    nei_y_1.append(np.mean(df[df["neighbourhood"] == nei_1]["price"].values))

for neigh_1 in nei_x_1:
    if (
        df[df["neighbourhood"] == neigh_1]["neighbourhood_group"].values[0]
        == "Manhattan"
    ):
        colors_1.append("red")
    elif (
        df[df["neighbourhood"] == neigh_1]["neighbourhood_group"].values[0]
        == "Brooklyn"
    ):
        colors_1.append("blue")
    elif (
        df[df["neighbourhood"] == neigh_1]["neighbourhood_group"].values[0] == "Queens"
    ):
        colors_1.append("green")
    elif df[df["neighbourhood"] == neigh_1]["neighbourhood_group"].values[0] == "Bronx":
        colors_1.append("orange")
    elif (
        df[df["neighbourhood"] == neigh_1]["neighbourhood_group"].values[0]
        == "Staten Island"
    ):
        colors_1.append("purple")

nei_x_1, nei_y_1, colors_1

(['Bedford-Stuyvesant',
  'Williamsburg',
  'Harlem',
  'Bushwick',
  "Hell's Kitchen",
  'Upper East Side',
  'Upper West Side',
  'Midtown',
  'East Village',
  'Crown Heights',
  'East Harlem',
  'Chelsea',
  'Greenpoint',
  'Financial District',
  'Washington Heights',
  'Astoria',
  'Lower East Side',
  'East Flatbush',
  'West Village',
  'Flushing',
  'Flatbush',
  'Murray Hill',
  'Long Island City',
  'Prospect-Lefferts Gardens',
  'Clinton Hill',
  'Park Slope',
  'Fort Greene',
  'Kips Bay',
  'Ridgewood',
  'Sunset Park',
  'Sunnyside',
  'SoHo',
  'Theater District',
  'Chinatown',
  'East New York',
  'Jamaica',
  'Ditmars Steinway',
  'Greenwich Village',
  'Gramercy',
  'Prospect Heights',
  'Elmhurst',
  'Woodside',
  'South Slope',
  'East Elmhurst',
  'Inwood',
  'Gowanus',
  'Jackson Heights',
  'Canarsie',
  'Sheepshead Bay',
  'Nolita',
  'Morningside Heights',
  'Carroll Gardens',
  'Tribeca',
  'Cypress Hills',
  'Borough Park',
  'Bay Ridge',
  'Kensington',
  'Boerum Hill',
  'Forest Hills',
  'Maspeth',
  'Windsor Terrace',
  'Rego Park',
  'Richmond Hill',
  'Brooklyn Heights',
  'Little Italy',
  'Springfield Gardens',
  'Woodhaven',
  'Flatlands',
  'Arverne',
  'St. Albans',
  'Midwood',
  'Brighton Beach',
  'Corona',
  'Cobble Hill',
  'Kingsbridge',
  'Fordham',
  'Bensonhurst',
  'Rosedale',
  'NoHo',
  'Red Hook',
  'Mott Haven',
  'Ozone Park',
  'Queens Village',
  'Rockaway Beach',
  'Flatiron District',
  'Brownsville',
  'Briarwood',
  'Two Bridges',
  'Gravesend',
  'Longwood',
  'Glendale',
  'Wakefield',
  'St. George',
  'Fort Hamilton',
  'Port Morris',
  'Concourse',
  'Downtown Brooklyn',
  'South Ozone Park',
  'Tompkinsville',
  'Allerton',
  'Bayside',
  'Roosevelt Island',
  'Battery Park City',
  'Williamsbridge',
  'Parkchester',
  'Middle Village',
  'Claremont Village',
  'Civic Center',
  'Fresh Meadows',
  'Kew Gardens',
  'Concord',
  'Columbia St',
  'Pelham Gardens',
  'Far Rockaway',
  'Stapleton',
  'Highbridge',
  'Concourse Village',
  'Throgs Neck',
  'Norwood',
  'Vinegar Hill',
  'Arrochar',
  'Clason Point',
  'DUMBO',
  'Cambria Heights',
  'Kew Gardens Hills',
  'Randall Manor',
  'Jamaica Estates',
  'West Brighton',
  'Stuyvesant Town',
  'City Island',
  'Belmont',
  'Bayswater',
  'Hunts Point',
  'Pelham Bay',
  'Howard Beach',
  'Mount Hope',
  'Laurelton',
  'College Point',
  'Bath Beach',
  'University Heights',
  'Coney Island',
  'Morrisania',
  'Morris Heights',
  'Clifton',
  'Eastchester',
  'Edenwald',
  'Bronxdale',
  'Morris Park',
  'Hollis',
  'Soundview',
  'Schuylerville',
  'Bellerose',
  'Van Nest',
  'Bergen Beach',
  'Great Kills',
  'Whitestone',
  'Edgemere',
  'East Morrisania',
  'Dyker Heights',
  'Castle Hill',
  'Westchester Square',
  'Woodlawn',
  'Douglaston',
  'Mariners Harbor',
  'Belle Harbor',
  'North Riverdale',
  'Riverdale',
  'Melrose',
  'South Beach',
  'Unionport',
  'Tottenville',
  'Fieldston',
  'Tremont',
  'Bay Terrace',
  'Rosebank',
  'Navy Yard',
  'Dongan Hills',
  'Jamaica Hills',
  'Marble Hill',
  'Baychester',
  'Grant City',
  'New Springville',
  'Grymes Hill',
  'Manhattan Beach',
  'New Brighton',
  'Port Richmond',
  'Shore Acres',
  'Little Neck',
  'Midland Beach',
  'Mill Basin',
  "Bull's Head",
  'Oakwood',
  'Spuyten Duyvil',
  'Emerson Hill',
  'New Dorp Beach',
  'Todt Hill',
  "Prince's Bay",
  'Arden Heights',
  'Olinville',
  'Breezy Point',
  'Eltingville',
  'Neponsit',
  'Huguenot',
  'Sea Gate',
  'Mount Eden',
  'Holliswood',
  'Castleton Corners',
  'Westerleigh',
  'Lighthouse Hill',
  'Co-op City',
  'West Farms',
  'Howland Hook',
  'Graniteville',
  'Rossville',
  'Fort Wadsworth',
  'Willowbrook',
  'Silver Lake',
  'Richmondtown'],
 [115.16881547139404,
  161.09259259259258,
  129.64302191464822,
  91.28295376121463,
  213.18326417704012,
  205.82465753424657,
  239.28374655647383,
  302.2907083716651,
  202.12434691745037,
  128.28618421052633,
  133.02445652173913,
  264.40651558073654,
  153.7965811965812,
  240.36888111888112,
  95.57116788321167,
  110.47627737226277,
  215.59245283018868,
  105.92609699769054,
  298.57655502392345,
  92.37940379403794,
  97.83923705722071,
  231.18032786885246,
  136.98319327731093,
  122.46153846153847,
  206.28571428571428,
  198.57093425605535,
  158.3275261324042,
  209.21942446043167,
  80.71841155234657,
  118.19277108433735,
  82.73877551020408,
  319.4016393442623,
  245.35564853556485,
  178.08849557522123,
  85.75829383886256,
  98.62085308056872,
  96.54285714285714,
  282.487922705314,
  247.9030612244898,
  208.36507936507937,
  83.29608938547486,
  86.32,
  150.26190476190476,
  81.0122699386503,
  94.25641025641026,
  176.86184210526315,
  80.84666666666666,
  105.24285714285715,
  111.0909090909091,
  275.64885496183206,
  129.40625,
  187.5327868852459,
  561.4628099173553,
  97.78632478632478,
  65.34821428571429,
  169.97169811320754,
  98.93137254901961,
  200.62626262626262,
  132.84848484848484,
  85.8061224489796,
  142.3978494623656,
  91.52941176470588,
  89.03614457831326,
  238.10843373493975,
  170.7125,
  94.34177215189874,
  66.54430379746836,
  129.8918918918919,
  175.0958904109589,
  103.02777777777777,
  87.20289855072464,
  137.96875,
  58.725806451612904,
  242.1551724137931,
  79.70689655172414,
  71.98214285714286,
  80.61818181818182,
  77.33333333333333,
  331.49056603773585,
  146.62264150943398,
  91.11538461538461,
  89.0,
  86.90196078431373,
  136.26530612244898,
  381.57142857142856,
  82.14583333333333,
  113.35416666666667,
  126.57446808510639,
  86.82608695652173,
  82.81818181818181,
  88.38095238095238,
  92.0,
  123.9047619047619,
  94.0,
  78.73170731707317,
  83.12820512820512,
  173.1578947368421,
  84.0,
  77.56756756756756,
  91.70270270270271,
  163.02777777777777,
  147.4857142857143,
  511.88235294117646,
  101.88235294117646,
  59.193548387096776,
  111.44827586206897,
  87.46428571428571,
  236.0,
  98.48148148148148,
  85.3076923076923,
  58.19230769230769,
  186.30769230769232,
  87.92307692307692,
  166.96,
  101.36,
  69.83333333333333,
  74.04166666666667,
  93.26086956521739,
  73.86363636363636,
  185.1904761904762,
  115.0,
  100.9,
  216.2,
  82.9,
  124.26315789473684,
  336.0,
  151.44444444444446,
  80.55555555555556,
  131.16666666666666,
  178.23529411764707,
  85.82352941176471,
  87.47058823529412,
  44.625,
  109.25,
  125.8125,
  85.375,
  100.875,
  91.8,
  76.33333333333333,
  69.4,
  137.71428571428572,
  72.28571428571429,
  75.64285714285714,
  85.64285714285714,
  141.69230769230768,
  82.0,
  54.92307692307692,
  73.15384615384616,
  87.76923076923077,
  54.75,
  67.91666666666667,
  104.5,
  113.81818181818181,
  106.7,
  100.6,
  114.3,
  84.7,
  85.0,
  97.7,
  63.0,
  130.0,
  60.111111111111114,
  82.75,
  94.625,
  171.5,
  75.375,
  567.25,
  97.57142857142857,
  99.14285714285714,
  137.14285714285714,
  144.85714285714286,
  77.57142857142857,
  55.57142857142857,
  142.0,
  108.0,
  146.16666666666666,
  66.83333333333333,
  157.0,
  110.66666666666667,
  78.0,
  57.666666666666664,
  66.66666666666667,
  152.33333333333334,
  99.83333333333333,
  101.8,
  48.8,
  120.8,
  75.2,
  90.2,
  179.75,
  55.0,
  90.0,
  154.75,
  64.0,
  56.25,
  82.33333333333333,
  484.3333333333333,
  76.0,
  43.666666666666664,
  213.33333333333334,
  141.66666666666666,
  274.6666666666667,
  118.33333333333333,
  569.6666666666666,
  42.666666666666664,
  147.66666666666666,
  136.33333333333334,
  71.5,
  157.5,
  77.5,
  122.0,
  100.0,
  67.5,
  75.0,
  800.0,
  249.0,
  80.0,
  78.0],
 ['blue',
  'blue',
  'red',
  'blue',
  'red',
  'red',
  'red',
  'red',
  'red',
  'blue',
  'red',
  'red',
  'blue',
  'red',
  'red',
  'green',
  'red',
  'blue',
  'red',
  'green',
  'blue',
  'red',
  'green',
  'blue',
  'blue',
  'blue',
  'blue',
  'red',
  'green',
  'blue',
  'green',
  'red',
  'red',
  'red',
  'blue',
  'green',
  'green',
  'red',
  'red',
  'blue',
  'green',
  'green',
  'blue',
  'green',
  'red',
  'blue',
  'green',
  'blue',
  'blue',
  'red',
  'red',
  'blue',
  'red',
  'blue',
  'blue',
  'blue',
  'blue',
  'blue',
  'green',
  'green',
  'blue',
  'green',
  'green',
  'blue',
  'red',
  'green',
  'green',
  'blue',
  'green',
  'green',
  'blue',
  'blue',
  'green',
  'blue',
  'orange',
  'orange',
  'blue',
  'green',
  'red',
  'blue',
  'orange',
  'green',
  'green',
  'green',
  'red',
  'blue',
  'green',
  'red',
  'blue',
  'orange',
  'green',
  'orange',
  'purple',
  'blue',
  'orange',
  'orange',
  'blue',
  'green',
  'purple',
  'orange',
  'green',
  'red',
  'red',
  'orange',
  'orange',
  'green',
  'orange',
  'red',
  'green',
  'green',
  'purple',
  'blue',
  'orange',
  'green',
  'purple',
  'orange',
  'orange',
  'orange',
  'orange',
  'blue',
  'purple',
  'orange',
  'blue',
  'green',
  'green',
  'purple',
  'green',
  'purple',
  'red',
  'orange',
  'orange',
  'green',
  'orange',
  'orange',
  'green',
  'orange',
  'green',
  'green',
  'blue',
  'orange',
  'blue',
  'orange',
  'orange',
  'purple',
  'orange',
  'orange',
  'orange',
  'orange',
  'green',
  'orange',
  'orange',
  'green',
  'orange',
  'blue',
  'purple',
  'green',
  'green',
  'orange',
  'blue',
  'orange',
  'orange',
  'orange',
  'green',
  'purple',
  'green',
  'orange',
  'orange',
  'orange',
  'purple',
  'orange',
  'purple',
  'orange',
  'orange',
  'green',
  'purple',
  'blue',
  'purple',
  'green',
  'red',
  'orange',
  'purple',
  'purple',
  'purple',
  'blue',
  'purple',
  'purple',
  'purple',
  'green',
  'purple',
  'blue',
  'purple',
  'purple',
  'orange',
  'purple',
  'purple',
  'purple',
  'purple',
  'purple',
  'orange',
  'green',
  'purple',
  'green',
  'purple',
  'blue',
  'orange',
  'green',
  'purple',
  'purple',
  'purple',
  'orange',
  'orange',
  'purple',
  'purple',
  'purple',
  'purple',
  'purple',
  'purple',
  'purple'])

In [22]:
### cell 16 ###

nei_x_aver_h_1 = []
nei_x_aver_l_1 = []
nei_y_aver_h_1 = []
nei_y_aver_l_1 = []
for nei_2 in df["neighbourhood"].value_counts().index:
    if np.mean(df[df["neighbourhood"] == nei_2]["price"].values) >= round(
        np.mean(nei_y_1), 3
    ):
        nei_x_aver_h_1.append(nei_2)
        nei_y_aver_h_1.append(np.mean(df[df["neighbourhood"] == nei_2]["price"].values))
    elif np.mean(df[df["neighbourhood"] == nei_2]["price"].values) < round(
        np.mean(nei_y_1), 3
    ):
        nei_x_aver_l_1.append(nei_2)
        nei_y_aver_l_1.append(np.mean(df[df["neighbourhood"] == nei_2]["price"].values))

nei_x_aver_h_1, nei_x_aver_l_1, nei_y_aver_h_1, nei_y_aver_l_1

(['Williamsburg',
  "Hell's Kitchen",
  'Upper East Side',
  'Upper West Side',
  'Midtown',
  'East Village',
  'Chelsea',
  'Greenpoint',
  'Financial District',
  'Lower East Side',
  'West Village',
  'Murray Hill',
  'Clinton Hill',
  'Park Slope',
  'Fort Greene',
  'Kips Bay',
  'SoHo',
  'Theater District',
  'Chinatown',
  'Greenwich Village',
  'Gramercy',
  'Prospect Heights',
  'South Slope',
  'Gowanus',
  'Nolita',
  'Carroll Gardens',
  'Tribeca',
  'Bay Ridge',
  'Boerum Hill',
  'Windsor Terrace',
  'Brooklyn Heights',
  'Little Italy',
  'Arverne',
  'Brighton Beach',
  'Cobble Hill',
  'NoHo',
  'Red Hook',
  'Flatiron District',
  'Downtown Brooklyn',
  'Bayside',
  'Roosevelt Island',
  'Battery Park City',
  'Civic Center',
  'Columbia St',
  'Far Rockaway',
  'Vinegar Hill',
  'DUMBO',
  'Randall Manor',
  'Jamaica Estates',
  'City Island',
  'Coney Island',
  'Eastchester',
  'Belle Harbor',
  'Riverdale',
  'Unionport',
  'Tottenville',
  'Bay Terrace',
  'Navy Yard',
  'Jamaica Hills',
  'Grymes Hill',
  'Mill Basin',
  'Spuyten Duyvil',
  "Prince's Bay",
  'Breezy Point',
  'Eltingville',
  'Neponsit',
  'Sea Gate',
  'Holliswood',
  'Lighthouse Hill',
  'Fort Wadsworth',
  'Willowbrook'],
 ['Bedford-Stuyvesant',
  'Harlem',
  'Bushwick',
  'Crown Heights',
  'East Harlem',
  'Washington Heights',
  'Astoria',
  'East Flatbush',
  'Flushing',
  'Flatbush',
  'Long Island City',
  'Prospect-Lefferts Gardens',
  'Ridgewood',
  'Sunset Park',
  'Sunnyside',
  'East New York',
  'Jamaica',
  'Ditmars Steinway',
  'Elmhurst',
  'Woodside',
  'East Elmhurst',
  'Inwood',
  'Jackson Heights',
  'Canarsie',
  'Sheepshead Bay',
  'Morningside Heights',
  'Cypress Hills',
  'Borough Park',
  'Kensington',
  'Forest Hills',
  'Maspeth',
  'Rego Park',
  'Richmond Hill',
  'Springfield Gardens',
  'Woodhaven',
  'Flatlands',
  'St. Albans',
  'Midwood',
  'Corona',
  'Kingsbridge',
  'Fordham',
  'Bensonhurst',
  'Rosedale',
  'Mott Haven',
  'Ozone Park',
  'Queens Village',
  'Rockaway Beach',
  'Brownsville',
  'Briarwood',
  'Two Bridges',
  'Gravesend',
  'Longwood',
  'Glendale',
  'Wakefield',
  'St. George',
  'Fort Hamilton',
  'Port Morris',
  'Concourse',
  'South Ozone Park',
  'Tompkinsville',
  'Allerton',
  'Williamsbridge',
  'Parkchester',
  'Middle Village',
  'Claremont Village',
  'Fresh Meadows',
  'Kew Gardens',
  'Concord',
  'Pelham Gardens',
  'Stapleton',
  'Highbridge',
  'Concourse Village',
  'Throgs Neck',
  'Norwood',
  'Arrochar',
  'Clason Point',
  'Cambria Heights',
  'Kew Gardens Hills',
  'West Brighton',
  'Stuyvesant Town',
  'Belmont',
  'Bayswater',
  'Hunts Point',
  'Pelham Bay',
  'Howard Beach',
  'Mount Hope',
  'Laurelton',
  'College Point',
  'Bath Beach',
  'University Heights',
  'Morrisania',
  'Morris Heights',
  'Clifton',
  'Edenwald',
  'Bronxdale',
  'Morris Park',
  'Hollis',
  'Soundview',
  'Schuylerville',
  'Bellerose',
  'Van Nest',
  'Bergen Beach',
  'Great Kills',
  'Whitestone',
  'Edgemere',
  'East Morrisania',
  'Dyker Heights',
  'Castle Hill',
  'Westchester Square',
  'Woodlawn',
  'Douglaston',
  'Mariners Harbor',
  'North Riverdale',
  'Melrose',
  'South Beach',
  'Fieldston',
  'Tremont',
  'Rosebank',
  'Dongan Hills',
  'Marble Hill',
  'Baychester',
  'Grant City',
  'New Springville',
  'Manhattan Beach',
  'New Brighton',
  'Port Richmond',
  'Shore Acres',
  'Little Neck',
  'Midland Beach',
  "Bull's Head",
  'Oakwood',
  'Emerson Hill',
  'New Dorp Beach',
  'Todt Hill',
  'Arden Heights',
  'Olinville',
  'Huguenot',
  'Mount Eden',
  'Castleton Corners',
  'Westerleigh',
  'Co-op City',
  'West Farms',
  'Howland Hook',
  'Graniteville',
  'Rossville',
  'Silver Lake',
  'Richmondtown'],
 [161.09259259259258,
  213.18326417704012,
  205.82465753424657,
  239.28374655647383,
  302.2907083716651,
  202.12434691745037,
  264.40651558073654,
  153.7965811965812,
  240.36888111888112,
  215.59245283018868,
  298.57655502392345,
  231.18032786885246,
  206.28571428571428,
  198.57093425605535,
  158.3275261324042,
  209.21942446043167,
  319.4016393442623,
  245.35564853556485,
  178.08849557522123,
  282.487922705314,
  247.9030612244898,
  208.36507936507937,
  150.26190476190476,
  176.86184210526315,
  275.64885496183206,
  187.5327868852459,
  561.4628099173553,
  169.97169811320754,
  200.62626262626262,
  142.3978494623656,
  238.10843373493975,
  170.7125,
  175.0958904109589,
  137.96875,
  242.1551724137931,
  331.49056603773585,
  146.62264150943398,
  381.57142857142856,
  173.1578947368421,
  163.02777777777777,
  147.4857142857143,
  511.88235294117646,
  236.0,
  186.30769230769232,
  166.96,
  185.1904761904762,
  216.2,
  336.0,
  151.44444444444446,
  178.23529411764707,
  137.71428571428572,
  141.69230769230768,
  171.5,
  567.25,
  137.14285714285714,
  144.85714285714286,
  142.0,
  146.16666666666666,
  157.0,
  152.33333333333334,
  179.75,
  154.75,
  484.3333333333333,
  213.33333333333334,
  141.66666666666666,
  274.6666666666667,
  569.6666666666666,
  147.66666666666666,
  157.5,
  800.0,
  249.0],
 [115.16881547139404,
  129.64302191464822,
  91.28295376121463,
  128.28618421052633,
  133.02445652173913,
  95.57116788321167,
  110.47627737226277,
  105.92609699769054,
  92.37940379403794,
  97.83923705722071,
  136.98319327731093,
  122.46153846153847,
  80.71841155234657,
  118.19277108433735,
  82.73877551020408,
  85.75829383886256,
  98.62085308056872,
  96.54285714285714,
  83.29608938547486,
  86.32,
  81.0122699386503,
  94.25641025641026,
  80.84666666666666,
  105.24285714285715,
  111.0909090909091,
  129.40625,
  97.78632478632478,
  65.34821428571429,
  98.93137254901961,
  132.84848484848484,
  85.8061224489796,
  91.52941176470588,
  89.03614457831326,
  94.34177215189874,
  66.54430379746836,
  129.8918918918919,
  103.02777777777777,
  87.20289855072464,
  58.725806451612904,
  79.70689655172414,
  71.98214285714286,
  80.61818181818182,
  77.33333333333333,
  91.11538461538461,
  89.0,
  86.90196078431373,
  136.26530612244898,
  82.14583333333333,
  113.35416666666667,
  126.57446808510639,
  86.82608695652173,
  82.81818181818181,
  88.38095238095238,
  92.0,
  123.9047619047619,
  94.0,
  78.73170731707317,
  83.12820512820512,
  84.0,
  77.56756756756756,
  91.70270270270271,
  101.88235294117646,
  59.193548387096776,
  111.44827586206897,
  87.46428571428571,
  98.48148148148148,
  85.3076923076923,
  58.19230769230769,
  87.92307692307692,
  101.36,
  69.83333333333333,
  74.04166666666667,
  93.26086956521739,
  73.86363636363636,
  115.0,
  100.9,
  82.9,
  124.26315789473684,
  80.55555555555556,
  131.16666666666666,
  85.82352941176471,
  87.47058823529412,
  44.625,
  109.25,
  125.8125,
  85.375,
  100.875,
  91.8,
  76.33333333333333,
  69.4,
  72.28571428571429,
  75.64285714285714,
  85.64285714285714,
  82.0,
  54.92307692307692,
  73.15384615384616,
  87.76923076923077,
  54.75,
  67.91666666666667,
  104.5,
  113.81818181818181,
  106.7,
  100.6,
  114.3,
  84.7,
  85.0,
  97.7,
  63.0,
  130.0,
  60.111111111111114,
  82.75,
  94.625,
  75.375,
  97.57142857142857,
  99.14285714285714,
  77.57142857142857,
  55.57142857142857,
  108.0,
  66.83333333333333,
  110.66666666666667,
  78.0,
  57.666666666666664,
  66.66666666666667,
  99.83333333333333,
  101.8,
  48.8,
  120.8,
  75.2,
  90.2,
  55.0,
  90.0,
  64.0,
  56.25,
  82.33333333333333,
  76.0,
  43.666666666666664,
  118.33333333333333,
  42.666666666666664,
  136.33333333333334,
  71.5,
  77.5,
  122.0,
  100.0,
  67.5,
  75.0,
  80.0,
  78.0])

In [23]:
### cell 17 ###

colors_2 = []
for neigh_2 in nei_x_aver_h_1:
    if (
        df[df["neighbourhood"] == neigh_2]["neighbourhood_group"].values[0]
        == "Manhattan"
    ):
        colors_2.append("red")
    elif (
        df[df["neighbourhood"] == neigh_2]["neighbourhood_group"].values[0]
        == "Brooklyn"
    ):
        colors_2.append("blue")
    elif (
        df[df["neighbourhood"] == neigh_2]["neighbourhood_group"].values[0] == "Queens"
    ):
        colors_2.append("green")
    elif df[df["neighbourhood"] == neigh_2]["neighbourhood_group"].values[0] == "Bronx":
        colors_2.append("orange")
    elif (
        df[df["neighbourhood"] == neigh_2]["neighbourhood_group"].values[0]
        == "Staten Island"
    ):
        colors_2.append("purple")
colors_2

['blue',
 'red',
 'red',
 'red',
 'red',
 'red',
 'red',
 'blue',
 'red',
 'red',
 'red',
 'red',
 'blue',
 'blue',
 'blue',
 'red',
 'red',
 'red',
 'red',
 'red',
 'red',
 'blue',
 'blue',
 'blue',
 'red',
 'blue',
 'red',
 'blue',
 'blue',
 'blue',
 'blue',
 'red',
 'green',
 'blue',
 'blue',
 'red',
 'blue',
 'red',
 'blue',
 'green',
 'red',
 'red',
 'red',
 'blue',
 'green',
 'blue',
 'blue',
 'purple',
 'green',
 'orange',
 'blue',
 'orange',
 'green',
 'orange',
 'orange',
 'purple',
 'green',
 'blue',
 'green',
 'purple',
 'blue',
 'orange',
 'purple',
 'green',
 'purple',
 'green',
 'blue',
 'green',
 'purple',
 'purple',
 'purple']

In [24]:
### cell 18 ###

colors_3 = []
for neigh_3 in nei_x_aver_h_1:
    if (
        df[df["neighbourhood"] == neigh_3]["neighbourhood_group"].values[0]
        == "Manhattan"
    ):
        colors_3.append("red")
    elif (
        df[df["neighbourhood"] == neigh_3]["neighbourhood_group"].values[0]
        == "Brooklyn"
    ):
        colors_3.append("blue")
    elif (
        df[df["neighbourhood"] == neigh_3]["neighbourhood_group"].values[0] == "Queens"
    ):
        colors_3.append("green")
    elif df[df["neighbourhood"] == neigh_3]["neighbourhood_group"].values[0] == "Bronx":
        colors_3.append("orange")
    elif (
        df[df["neighbourhood"] == neigh_3]["neighbourhood_group"].values[0]
        == "Staten Island"
    ):
        colors_3.append("purple")
colors_3

['blue',
 'red',
 'red',
 'red',
 'red',
 'red',
 'red',
 'blue',
 'red',
 'red',
 'red',
 'red',
 'blue',
 'blue',
 'blue',
 'red',
 'red',
 'red',
 'red',
 'red',
 'red',
 'blue',
 'blue',
 'blue',
 'red',
 'blue',
 'red',
 'blue',
 'blue',
 'blue',
 'blue',
 'red',
 'green',
 'blue',
 'blue',
 'red',
 'blue',
 'red',
 'blue',
 'green',
 'red',
 'red',
 'red',
 'blue',
 'green',
 'blue',
 'blue',
 'purple',
 'green',
 'orange',
 'blue',
 'orange',
 'green',
 'orange',
 'orange',
 'purple',
 'green',
 'blue',
 'green',
 'purple',
 'blue',
 'orange',
 'purple',
 'green',
 'purple',
 'green',
 'blue',
 'green',
 'purple',
 'purple',
 'purple']

In [25]:
### cell 19 ###

x_2 = df["calculated_host_listings_count"].value_counts().sort_index().index.astype(str)
y_2 = df["calculated_host_listings_count"].value_counts().sort_index().values

x_2, y_2

(Index(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13',
        '14', '15', '16', '17', '18', '19', '20', '21', '23', '25', '26', '27',
        '28', '29', '30', '31', '32', '33', '34', '37', '39', '43', '47', '49',
        '50', '52', '65', '87', '91', '96', '103', '121', '232', '327'],
       dtype='object'),
 array([173930,  49220,  24020,  12870,   7590,   5380,   3710,   3840,
          2320,   2060,   1080,   1510,   1280,    580,    700,    160,
           680,    540,    190,    400,    200,    660,    490,    260,
           260,    560,    290,    300,    620,    320,    980,    670,
           210,    380,    430,    470,    980,    500,   1020,    650,
           850,    860,   1880,    920,   1210,   2320,   3270]))

In [26]:
end_time = time.time()
print(end_time - start_time)

74.04992842674255