In [1]:
%load_ext cudf.pandas

In [2]:
import sys, os
sys.path.insert(0, os.path.abspath('/home/ElasticNotebook'))
%load_ext ElasticNotebook
from elastic.core.common.pandas import compare_df
import pickle
import cudf

Enabled rmm statistics

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
# STEFANOS: Disable pip install
# !pip install lazypredict
# !pip install --upgrade pandas
# !pip install fast-tabnet
# !pip install fastai
# !pip install pandas-profiling

In [5]:
#A program that takes a csv and trains models on it. Streamlined model selection.
#==============================================================================

# STEFANOS: Disable unneeded modules
# #LazyPredict
# import lazypredict
# from lazypredict.Supervised import LazyRegressor
# from lazypredict.Supervised import LazyClassifier
# #Baysian Optimization
# from bayes_opt import BayesianOptimization
#Pandas stack
import os
# STEFANOS: Conditionally import Modin Pandas
if "IREWR_WITH_MODIN" in os.environ and os.environ["IREWR_WITH_MODIN"] == "True":
    # STEFANOS: Import Modin Pandas
    import os
    os.environ["MODIN_ENGINE"] = "ray"
    import ray
    ray.init(num_cpus=int(os.environ['MODIN_CPUS']), runtime_env={'env_vars': {'__MODIN_AUTOIMPORT_PANDAS__': '1'}})
    import modin.pandas as pd
else:
    # STEFANOS: Import regular Pandas
    import pandas as pd
# import pandas_profiling
import numpy as np
# STEFANOS: Disable unneeded modules
# #FastAI
from fastai.tabular.all import *
from fastai.tabular.core import *
# #Plots
# import matplotlib.pyplot as plt
# import seaborn as sns
#System
import os
import sys
import traceback
#Fit an xgboost model
# STEFANOS: Disable unneeded modules
# from xgboost import XGBRegressor
# from xgboost import XGBClassifier
# from xgboost import plot_importance
# from sklearn.metrics import mean_squared_error
# from sklearn.metrics import roc_auc_score
#Random
import random

#TabNet
from fast_tabnet.core import *

import shutil

In [6]:
# STEFANOS: Disable matplotlib inline
# %matplotlib inline

In [7]:
# For Styling
# STEFANOS: Disbale plotting
# plt.style.use('seaborn-bright')

In [8]:
#Project Variables
#===================================================================================================
PROJECT_NAME = 'superstore'
VARIABLE_FILES = False
#Maximum amount of rows to take

## -- STEFANOS -- Remove sample

# SAMPLE_COUNT = 4000
FASTAI_LEARNING_RATE = 1e-1
AUTO_ADJUST_LEARNING_RATE = False
#Set to True automatically infer if variables are categorical or continuous
ENABLE_BREAKPOINT = True
#When trying to declare a column a continuous variable, if it fails, convert it to a categorical variable
CONVERT_TO_CAT = False
REGRESSOR = True
SEP_DOLLAR = False
SEP_COMMA = True
SHUFFLE_DATA = True

In [9]:
%%time
### cell 0 ###

# input_dir = f'/home/dias-benchmarks/notebooks/dataranch/supermarket-sales-prediction-xgboost-fastai/input/{PROJECT_NAME}'
# # STEFANOS: Change the working path
# # param_dir = f'/kaggle/working/{PROJECT_NAME}'
param_dir = f'./working/{PROJECT_NAME}'
TARGET = ''
PARAM_DIR = param_dir
# print(f'param_dir: {param_dir}')
# if not os.path.exists(param_dir):
#     os.makedirs(param_dir)
# #rename any file in param_dir/file that ends with csv to data.csv
# for file in os.listdir(input_dir):
#     if file.endswith('.csv'):
#         print('CSV!')
#         if 'classification_results' not in file and 'regression_results' not in file:
#             #os.rename(f'{input_dir}/{file}', f'{param_dir}/data.csv')
#             shutil.copy(f'{input_dir}/{file}', f'{param_dir}/data.csv')
#         #os.rename(f'{param_dir}/{file}', f'{param_dir}/data.csv')
try:
    # STEFANOS: Remove sample
#     df = pd.read_csv(f'{param_dir}/data.csv', nrows=SAMPLE_COUNT)
    df = pd.read_csv(f'{param_dir}/data.csv')
except:
    print(f'Please place a file named data.csv in {param_dir}')
    #sys.exit()

CPU times: user 29.6 ms, sys: 56.4 ms, total: 86 ms
Wall time: 83.9 ms

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_post 0 ##
pd_df['Ship Mode'] = df['Ship Mode']

In [ ]:
%%time
## Transfer_post 0 ##
pd_df['Segment'] = df['Segment']

In [ ]:
%%time
## Transfer_post 0 ##
pd_df['Country'] = df['Country']

In [ ]:
%%time
## Transfer_post 0 ##
pd_df['City'] = df['City']

In [ ]:
%%time
## Transfer_post 0 ##
pd_df['State'] = df['State']

In [ ]:
%%time
## Transfer_post 0 ##
pd_df['Postal Code'] = df['Postal Code']

In [ ]:
%%time
## Transfer_post 0 ##
pd_df['Region'] = df['Region']

In [ ]:
%%time
## Transfer_post 0 ##
pd_df['Category'] = df['Category']

In [ ]:
%%time
## Transfer_post 0 ##
pd_df['Sub-Category'] = df['Sub-Category']

In [ ]:
%%time
## Transfer_post 0 ##
pd_df['Sales'] = df['Sales']

In [ ]:
%%time
## Transfer_post 0 ##
pd_df['Quantity'] = df['Quantity']

In [ ]:
%%time
## Transfer_post 0 ##
pd_df['Discount'] = df['Discount']

In [ ]:
%%time
## Transfer_post 0 ##
pd_df['Profit'] = df['Profit']

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 1 ##
pd_df['Ship Mode'] = df['Ship Mode']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_df['Segment'] = df['Segment']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_df['Country'] = df['Country']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_df['City'] = df['City']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_df['State'] = df['State']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_df['Postal Code'] = df['Postal Code']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_df['Region'] = df['Region']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_df['Category'] = df['Category']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_df['Sub-Category'] = df['Sub-Category']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_df['Sales'] = df['Sales']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_df['Quantity'] = df['Quantity']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_df['Discount'] = df['Discount']

In [ ]:
%%time
## Transfer_pre 1 ##
pd_df['Profit'] = df['Profit']

In [10]:
%%time
### cell 1 ###

df

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 6.91 µs

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,25.2480,3,0.20,4.1028
9990,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,91.9600,2,0.00,15.6332
9991,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,258.5760,2,0.20,19.3932
9992,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,29.6000,4,0.00,13.3200
9993,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,243.1600,2,0.00,72.9480

# -- STEFANOS -- Replicate Data

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 2 ##
pd_df['Ship Mode'] = df['Ship Mode']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_df['Profit'] = df['Profit']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_df['Segment'] = df['Segment']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_df['Discount'] = df['Discount']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_df['Postal Code'] = df['Postal Code']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_df['Quantity'] = df['Quantity']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_df['Country'] = df['Country']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_df['Region'] = df['Region']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_df['State'] = df['State']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_df['Sub-Category'] = df['Sub-Category']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_df['Category'] = df['Category']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_df['City'] = df['City']

In [ ]:
%%time
## Transfer_pre 2 ##
pd_df['Sales'] = df['Sales']

In [11]:
%%time
### cell 2 ###

factor = 10
df = pd.concat([df]*factor)
df.info()

<class 'cudf.core.dataframe.DataFrame'>
Index: 99940 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ship Mode     99940 non-null  object
 1   Segment       99940 non-null  object
 2   Country       99940 non-null  object
 3   City          99940 non-null  object
 4   State         99940 non-null  object
 5   Postal Code   99940 non-null  int64
 6   Region        99940 non-null  object
 7   Category      99940 non-null  object
 8   Sub-Category  99940 non-null  object
 9   Sales         99940 non-null  float64
 10  Quantity      99940 non-null  int64
 11  Discount      99940 non-null  float64
 12  Profit        99940 non-null  float64
dtypes: float64(3), int64(2), object(8)
memory usage: 15.0+ MB
CPU times: user 35.8 ms, sys: 12.7 ms, total: 48.5 ms
Wall time: 44 ms

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 3 ##
pd_df['Ship Mode'] = df['Ship Mode']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_df['Profit'] = df['Profit']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_df['Segment'] = df['Segment']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_df['Discount'] = df['Discount']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_df['State'] = df['State']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_df['Quantity'] = df['Quantity']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_df['Country'] = df['Country']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_df['Region'] = df['Region']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_df['Sub-Category'] = df['Sub-Category']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_df['Postal Code'] = df['Postal Code']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_df['Category'] = df['Category']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_df['City'] = df['City']

In [ ]:
%%time
## Transfer_pre 3 ##
pd_df['Sales'] = df['Sales']

In [12]:
%%time
### cell 3 ###

if SEP_DOLLAR:
    #For every column in df_copy, if the column contains a $, make a new column with the value without the $
    for col in df_copy.columns:
        if '$' in df[col].to_string():
            df[col + '_no_dollar'] = df[col].str.replace('$', '').str.replace(',', '')
            #Try to convert this new column to a numeric type
            try:
                df[col + '_no_dollar'] = df[col + '_no_dollar'].apply(pd.to_numeric, errors='coerce').dropna()
            except Exception:
                print(f'{col} can not be converted to a float!')


if SEP_COMMA:
    #For every column in df_copy, if the column contains a %, make a new column with the value without the %
    for col in df.columns:
        if '%' in df[col].to_string() or ',' in df[col].to_string():
            df[col + '_processed'] = df[col].apply(str).str.replace('%', '').str.replace(',', '')
            #Try to convert this new column to a numeric type
            try:
                df[col + '_processed'] = df[col + '_processed'].apply(pd.to_numeric, errors='coerce').dropna()
            except Exception:
                print(f'{col} can not be converted to a float!')

CPU times: user 12.9 s, sys: 113 ms, total: 13 s
Wall time: 12.9 s

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 4 ##
pd_df['Ship Mode'] = df['Ship Mode']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_df['Segment'] = df['Segment']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_df['Country'] = df['Country']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_df['City'] = df['City']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_df['State'] = df['State']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_df['Postal Code'] = df['Postal Code']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_df['Region'] = df['Region']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_df['Category'] = df['Category']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_df['Sub-Category'] = df['Sub-Category']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_df['Sales'] = df['Sales']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_df['Quantity'] = df['Quantity']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_df['Discount'] = df['Discount']

In [ ]:
%%time
## Transfer_pre 4 ##
pd_df['Profit'] = df['Profit']

In [13]:
%%time
### cell 4 ###

df

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 7.87 µs

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,...,City_processed,State_processed,Postal Code_processed,Region_processed,Category_processed,Sub-Category_processed,Sales_processed,Quantity_processed,Discount_processed,Profit_processed
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,...,<NA>,<NA>,42420,<NA>,<NA>,<NA>,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,...,<NA>,<NA>,42420,<NA>,<NA>,<NA>,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,...,<NA>,<NA>,90036,<NA>,<NA>,<NA>,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,...,<NA>,<NA>,33311,<NA>,<NA>,<NA>,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,...,<NA>,<NA>,33311,<NA>,<NA>,<NA>,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,25.2480,...,<NA>,<NA>,33180,<NA>,<NA>,<NA>,25.2480,3,0.20,4.1028
9990,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,91.9600,...,<NA>,<NA>,92627,<NA>,<NA>,<NA>,91.9600,2,0.00,15.6332
9991,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,258.5760,...,<NA>,<NA>,92627,<NA>,<NA>,<NA>,258.5760,2,0.20,19.3932
9992,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,29.6000,...,<NA>,<NA>,92627,<NA>,<NA>,<NA>,29.6000,4,0.00,13.3200
9993,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,243.1600,...,<NA>,<NA>,92683,<NA>,<NA>,<NA>,243.1600,2,0.00,72.9480

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 5 ##
pd_df['Ship Mode'] = df['Ship Mode']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_df['Segment'] = df['Segment']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_df['Country'] = df['Country']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_df['City'] = df['City']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_df['State'] = df['State']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_df['Postal Code'] = df['Postal Code']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_df['Region'] = df['Region']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_df['Category'] = df['Category']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_df['Sub-Category'] = df['Sub-Category']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_df['Sales'] = df['Sales']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_df['Quantity'] = df['Quantity']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_df['Discount'] = df['Discount']

In [ ]:
%%time
## Transfer_pre 5 ##
pd_df['Profit'] = df['Profit']

In [14]:
%%time
### cell 5 ###

df.isna().sum()

CPU times: user 29.8 ms, sys: 12.1 ms, total: 41.9 ms
Wall time: 37.2 ms

Ship Mode                     0
Segment                       0
Country                       0
City                          0
State                         0
Postal Code                   0
Region                        0
Category                      0
Sub-Category                  0
Sales                         0
Quantity                      0
Discount                      0
Profit                        0
Ship Mode_processed       99940
Segment_processed         99940
Country_processed         99940
City_processed            99940
State_processed           99940
Postal Code_processed         0
Region_processed          99940
Category_processed        99940
Sub-Category_processed    99940
Sales_processed               0
Quantity_processed            0
Discount_processed            0
Profit_processed              0
dtype: int64

In [15]:
# df.profile_report()

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 6 ##
pd_df['Ship Mode'] = df['Ship Mode']

In [ ]:
%%time
## Transfer_pre 6 ##
pd_df['Segment'] = df['Segment']

In [ ]:
%%time
## Transfer_pre 6 ##
pd_df['Country'] = df['Country']

In [ ]:
%%time
## Transfer_pre 6 ##
pd_df['City'] = df['City']

In [ ]:
%%time
## Transfer_pre 6 ##
pd_df['State'] = df['State']

In [ ]:
%%time
## Transfer_pre 6 ##
pd_df['Postal Code'] = df['Postal Code']

In [ ]:
%%time
## Transfer_pre 6 ##
pd_df['Region'] = df['Region']

In [ ]:
%%time
## Transfer_pre 6 ##
pd_df['Category'] = df['Category']

In [ ]:
%%time
## Transfer_pre 6 ##
pd_df['Sub-Category'] = df['Sub-Category']

In [ ]:
%%time
## Transfer_pre 6 ##
pd_df['Sales'] = df['Sales']

In [ ]:
%%time
## Transfer_pre 6 ##
pd_df['Quantity'] = df['Quantity']

In [ ]:
%%time
## Transfer_pre 6 ##
pd_df['Discount'] = df['Discount']

In [ ]:
%%time
## Transfer_pre 6 ##
pd_df['Profit'] = df['Profit']

In [16]:
%%time
### cell 6 ###

# STEFANOS: Disable plotting
# sns.heatmap(df.corr())
_ = df.select_dtypes(include=['number']).corr()

CPU times: user 192 ms, sys: 16 ms, total: 208 ms
Wall time: 207 ms

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 7 ##
pd_df['Ship Mode'] = df['Ship Mode']

In [ ]:
%%time
## Transfer_pre 7 ##
pd_df['Segment'] = df['Segment']

In [ ]:
%%time
## Transfer_pre 7 ##
pd_df['Country'] = df['Country']

In [ ]:
%%time
## Transfer_pre 7 ##
pd_df['City'] = df['City']

In [ ]:
%%time
## Transfer_pre 7 ##
pd_df['State'] = df['State']

In [ ]:
%%time
## Transfer_pre 7 ##
pd_df['Postal Code'] = df['Postal Code']

In [ ]:
%%time
## Transfer_pre 7 ##
pd_df['Region'] = df['Region']

In [ ]:
%%time
## Transfer_pre 7 ##
pd_df['Category'] = df['Category']

In [ ]:
%%time
## Transfer_pre 7 ##
pd_df['Sub-Category'] = df['Sub-Category']

In [ ]:
%%time
## Transfer_pre 7 ##
pd_df['Sales'] = df['Sales']

In [ ]:
%%time
## Transfer_pre 7 ##
pd_df['Quantity'] = df['Quantity']

In [ ]:
%%time
## Transfer_pre 7 ##
pd_df['Discount'] = df['Discount']

In [ ]:
%%time
## Transfer_pre 7 ##
pd_df['Profit'] = df['Profit']

In [17]:
%%time
### cell 7 ###

# STEFANOS: Disable plotting
# df.head().style.background_gradient(cmap = "inferno")
df.head()

CPU times: user 4.95 ms, sys: 59 µs, total: 5.01 ms
Wall time: 3.84 ms

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,...,City_processed,State_processed,Postal Code_processed,Region_processed,Category_processed,Sub-Category_processed,Sales_processed,Quantity_processed,Discount_processed,Profit_processed
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,...,<NA>,<NA>,42420,<NA>,<NA>,<NA>,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,...,<NA>,<NA>,42420,<NA>,<NA>,<NA>,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,...,<NA>,<NA>,90036,<NA>,<NA>,<NA>,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,...,<NA>,<NA>,33311,<NA>,<NA>,<NA>,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,...,<NA>,<NA>,33311,<NA>,<NA>,<NA>,22.3680,2,0.20,2.5164

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 8 ##
pd_df['Ship Mode'] = df['Ship Mode']

In [ ]:
%%time
## Transfer_pre 8 ##
pd_df['Segment'] = df['Segment']

In [ ]:
%%time
## Transfer_pre 8 ##
pd_df['Country'] = df['Country']

In [ ]:
%%time
## Transfer_pre 8 ##
pd_df['City'] = df['City']

In [ ]:
%%time
## Transfer_pre 8 ##
pd_df['State'] = df['State']

In [ ]:
%%time
## Transfer_pre 8 ##
pd_df['Postal Code'] = df['Postal Code']

In [ ]:
%%time
## Transfer_pre 8 ##
pd_df['Region'] = df['Region']

In [ ]:
%%time
## Transfer_pre 8 ##
pd_df['Category'] = df['Category']

In [ ]:
%%time
## Transfer_pre 8 ##
pd_df['Sub-Category'] = df['Sub-Category']

In [ ]:
%%time
## Transfer_pre 8 ##
pd_df['Sales'] = df['Sales']

In [ ]:
%%time
## Transfer_pre 8 ##
pd_df['Quantity'] = df['Quantity']

In [ ]:
%%time
## Transfer_pre 8 ##
pd_df['Discount'] = df['Discount']

In [ ]:
%%time
## Transfer_pre 8 ##
pd_df['Profit'] = df['Profit']

In [18]:
%%time
### cell 8 ###

# STEFANOS: Disable plotting
# df.describe().T.style.background_gradient(cmap = "viridis")
df.describe().T

CPU times: user 494 ms, sys: 74.9 ms, total: 569 ms
Wall time: 503 ms

,count,mean,std,min,25%,50%,75%,max
Postal Code,99940.0,55190.379428,32062.249571,1040.000,23223.000,56430.5000,90008.000,99301.000
Sales,99940.0,229.858001,623.217037,0.444,17.280,54.4900,209.940,22638.480
Quantity,99940.0,3.789574,2.225009,1.000,2.000,3.0000,5.000,14.000
Discount,99940.0,0.156203,0.206443,0.000,0.000,0.2000,0.200,0.800
Profit,99940.0,28.656896,234.249559,-6599.978,1.728,8.6665,29.364,8399.976
Ship Mode_processed,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Segment_processed,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Country_processed,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City_processed,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
State_processed,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Postal Code_processed,99940.0,55190.379428,32062.249571,1040.000,23223.000,56430.5000,90008.000,99301.000
Region_processed,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category_processed,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sub-Category_processed,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sales_processed,99940.0,229.858001,623.217037,0.444,17.280,54.4900,209.940,22638.480
Quantity_processed,99940.0,3.789574,2.225009,1.000,2.000,3.0000,5.000,14.000
Discount_processed,99940.0,0.156203,0.206443,0.000,0.000,0.2000,0.200,0.800
Profit_processed,99940.0,28.656896,234.249559,-6599.978,1.728,8.6665,29.364,8399.976

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 9 ##
pd_df['Ship Mode'] = df['Ship Mode']

In [ ]:
%%time
## Transfer_pre 9 ##
pd_df['Segment'] = df['Segment']

In [ ]:
%%time
## Transfer_pre 9 ##
pd_df['Country'] = df['Country']

In [ ]:
%%time
## Transfer_pre 9 ##
pd_df['City'] = df['City']

In [ ]:
%%time
## Transfer_pre 9 ##
pd_df['State'] = df['State']

In [ ]:
%%time
## Transfer_pre 9 ##
pd_df['Postal Code'] = df['Postal Code']

In [ ]:
%%time
## Transfer_pre 9 ##
pd_df['Region'] = df['Region']

In [ ]:
%%time
## Transfer_pre 9 ##
pd_df['Category'] = df['Category']

In [ ]:
%%time
## Transfer_pre 9 ##
pd_df['Sub-Category'] = df['Sub-Category']

In [ ]:
%%time
## Transfer_pre 9 ##
pd_df['Sales'] = df['Sales']

In [ ]:
%%time
## Transfer_pre 9 ##
pd_df['Quantity'] = df['Quantity']

In [ ]:
%%time
## Transfer_pre 9 ##
pd_df['Discount'] = df['Discount']

In [ ]:
%%time
## Transfer_pre 9 ##
pd_df['Profit'] = df['Profit']

In [19]:
%%time
### cell 9 ###

df.columns

CPU times: user 187 µs, sys: 12 µs, total: 199 µs
Wall time: 204 µs

Index(['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Postal Code',
       'Region', 'Category', 'Sub-Category', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Ship Mode_processed', 'Segment_processed',
       'Country_processed', 'City_processed', 'State_processed',
       'Postal Code_processed', 'Region_processed', 'Category_processed',
       'Sub-Category_processed', 'Sales_processed', 'Quantity_processed',
       'Discount_processed', 'Profit_processed'],
      dtype='object')

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 10 ##
pd_df['Ship Mode'] = df['Ship Mode']

In [ ]:
%%time
## Transfer_pre 10 ##
pd_df['Profit'] = df['Profit']

In [ ]:
%%time
## Transfer_pre 10 ##
pd_df['Segment'] = df['Segment']

In [ ]:
%%time
## Transfer_pre 10 ##
pd_df['Discount'] = df['Discount']

In [ ]:
%%time
## Transfer_pre 10 ##
pd_df['Postal Code'] = df['Postal Code']

In [ ]:
%%time
## Transfer_pre 10 ##
pd_df['Quantity'] = df['Quantity']

In [ ]:
%%time
## Transfer_pre 10 ##
pd_df['Country'] = df['Country']

In [ ]:
%%time
## Transfer_pre 10 ##
pd_df['Region'] = df['Region']

In [ ]:
%%time
## Transfer_pre 10 ##
pd_df['State'] = df['State']

In [ ]:
%%time
## Transfer_pre 10 ##
pd_df['Sub-Category'] = df['Sub-Category']

In [ ]:
%%time
## Transfer_pre 10 ##
pd_df['Category'] = df['Category']

In [ ]:
%%time
## Transfer_pre 10 ##
pd_df['City'] = df['City']

In [ ]:
%%time
## Transfer_pre 10 ##
pd_df['Sales'] = df['Sales']

In [20]:
%%time
### cell 10 ###

target = ''
target_str = ''
#The column closest to the end isPARAM_DIR the target variable that can be represented as a float is the target variable
targets = []
#Loop through every possible target column (Continuous)
for i in range(len(df.columns)-1, 0, -1):
    try:
        df[df.columns[i]] = df[df.columns[i]].apply(pd.to_numeric, errors='coerce').dropna()
        target = df.columns[i]
        target_str = target.replace('/', '-')
    except:
        continue
    print(f'Target Variable: {target}')
    #Will be determined by the file name


    #===================================================================================================

    #Create project config files if they don't exist.
    if not os.path.exists(param_dir):
        #create param_dir
        os.makedirs(PARAM_DIR)
    if not os.path.exists(f'{PARAM_DIR}/cats.txt'):
        #create param_dir
        with open(f'{PARAM_DIR}/cats.txt', 'w') as f:
            f.write('')
    if not os.path.exists(f'{PARAM_DIR}/conts.txt'):
        #create param_dir
        with open(f'{PARAM_DIR}/conts.txt', 'w') as f:
            f.write('')
    if not os.path.exists(f'{PARAM_DIR}/cols_to_delete.txt'):
        with open(f'{PARAM_DIR}/cols_to_delete.txt', 'w') as f:
            f.write('')

    df = df.drop_duplicates()
    if SHUFFLE_DATA:
        df = df.sample(frac=1).reset_index(drop=True)

    # workaround for fastai/pytorch bug where bool is treated as object and thus erroring out.
    for n in df:
        if pd.api.types.is_bool_dtype(df[n]):
            df[n] = df[n].astype('uint8')

    with open(f'{PARAM_DIR}/cols_to_delete.txt', 'r') as f:
        cols_to_delete = f.read().splitlines()
    for col in cols_to_delete:
        try:
            del(df[col])
        except:
            pass
    #try to fill in missing values now, otherwise FastAI will do it for us later
    try:
        df = df.fillna(0)
    except:
        pass
    #print missing values
    #print(df.isna().sum().sort_values(ascending=False))
    #shrink df as much as possible
    df = df_shrink(df)


    #print types inside of df
    #print(df.dtypes)


    #Auto detect categorical and continuous variables
    #==============================================================================
    likely_cat = {}
    for var in df.columns:
        likely_cat[var] = 1.*df[var].nunique()/df[var].count() < 0.05 #or some other threshold

    cats = [var for var in df.columns if likely_cat[var]]
    conts = [var for var in df.columns if not likely_cat[var]]

    #remove target from lists
    try:
        conts.remove(target)
        cats.remove(target)
    except:
        pass
    #Convert target to float
    df[target] = df[target].apply(pd.to_numeric, errors='coerce').dropna()

    print('CATS=====================')
    print(cats)
    print('CONTS=====================')
    print(conts)

    #Populate categorical and continuous lists
    #==============================================================================

    if VARIABLE_FILES == True:
        with open(f'{PARAM_DIR}/cats.txt', 'r') as f:
            cats = f.read().splitlines()

        with open(f'{PARAM_DIR}/conts.txt', 'r') as f:
            conts = f.read().splitlines()

    #==============================================================================

    #==============================================================================
    procs = [Categorify, FillMissing, Normalize]
    #print(df.describe().T)
    # STEFANOS: Remove samples
#     df = df[0:SAMPLE_COUNT]
    splits = RandomSplitter()(range_of(df))

    print((len(cats)) + len(conts))
    #conts = []

    #Convert cont variables to floats
    #==============================================================================

    #Convert cont variables to floats
    #==============================================================================

    for var in conts:
        try:
            df[var] = df[var].apply(pd.to_numeric, errors='coerce').dropna()
        except:
            print(f'Could not convert {var} to float.')
            pass

    #==============================================================================

    #Experimental logic to add columns one-by-one to find a breakpoint
    #==============================================================================
    if ENABLE_BREAKPOINT == True:
        temp_procs = [Categorify, FillMissing]
        print('Looping through continuous variables to find breakpoint')
        cont_list = []
        for cont in conts:
            focus_cont = cont
            cont_list.append(cont)
            #print(focus_cont)
            try:
                to = TabularPandas(df, procs=procs, cat_names=cats, cont_names=cont_list, y_names=target, y_block=RegressionBlock(), splits=splits)
                del(to)
            except:
                print('Error with ', focus_cont)
                #remove focus_cont from list
                cont_list.remove(focus_cont)
                #traceback.print_exc()
                continue
        #convert all continuous variables to floats
        for var in cont_list:
            try:
                df[var] = df[var].apply(pd.to_numeric, errors='coerce').dropna()
            except:
                print(f'Could not convert {var} to float.')
                cont_list.remove(var)
                if CONVERT_TO_CAT == True:
                    cats.append(var)
                pass
        print(f'Continuous variables that made the cut : {cont_list}')
        print(f'Categorical variables that made the cut : {cats}')
        #shrink df as much as possible
        df = df_shrink(df)
        #print(df.dtypes)

    #==============================================================================

    #Creating tabular object + quick preprocessing
    #==============================================================================
    to = None
    if REGRESSOR == True:
        try:
            to = TabularPandas(df, procs, cats, conts, target, y_block=RegressionBlock(), splits=splits)
        except:
            conts = []
            to = TabularPandas(df, procs, cats, conts, target, y_block=RegressionBlock(), splits=splits)
    else:
        try:
            to = TabularPandas(df, procs, cats, conts, target, splits=splits)
        except:
            conts = []
            to = TabularPandas(df, procs, cats, conts, target, splits=splits)

### STEFANOS - Disabled ML code ###
            
#     #print(dir(to))
#     #print(to.xs)
#     dls = to.dataloaders()
#     print(f'Tabular Object size: {len(to)}')
#     try:
#         dls.one_batch()
#     except:
#         print(f'problem with getting one batch of {PROJECT_NAME}')
#     #==============================================================================

#     #Extracting train and test sets from tabular object
#     #==============================================================================

#     X_train, y_train = to.train.xs, to.train.ys.values.ravel()
#     X_test, y_test = to.valid.xs, to.valid.ys.values.ravel()

#     #Make sure target isn't in independent columns
#     if target in X_train and target in X_test:
#         del(X_train[target])
#         del(X_test[target])
#     #create dataframe from X_train and y_train
#     #export tabular object to csv
#     pd.DataFrame(X_train).to_csv(f'{PARAM_DIR}/X_train_{target_str}.csv', index=False)
#     pd.DataFrame(X_test).to_csv(f'{PARAM_DIR}/X_test_{target_str}.csv', index=False)
#     pd.DataFrame(y_train).to_csv(f'{PARAM_DIR}/y_train_{target_str}.csv', index=False)
#     pd.DataFrame(y_test).to_csv(f'{PARAM_DIR}/y_test_{target_str}.csv', index=False)

#     #==============================================================================

#     #==============================================================================

#     #Ready for model selection!

#     if REGRESSOR == True:
#         try:
#             reg = LazyRegressor(verbose=2, ignore_warnings=False, custom_metric=None)
#             models, predictions = reg.fit(X_train, X_test, y_train, y_test)
#             print(f'Project: {PROJECT_NAME}')
#             print(PROJECT_NAME)
#             print(f'Target: {target}')
#             print(target)
#             target_std = y_train.std()
#             print(f'Target Standard Deviation: {target_std}')
#             print(models)
#             models['project'] = PROJECT_NAME
#             models['target'] = target
#             models['target_std'] = target_std
#             #rename index of 
#             models.to_csv(f'{PARAM_DIR}/regression_results_{target_str}.csv', mode='a', header=True, index=True)
#         except:
#             print('Issue during lazypredict analysis')
#     else:
#         #TODO: remove this
#         try:
#             clf = LazyClassifier(verbose=2, ignore_warnings=False, custom_metric=None)
#             models, predictions = clf.fit(X_train, X_test, y_train, y_test)
#             print(f'Project: {PROJECT_NAME}')
#             print(PROJECT_NAME)
#             print(f'Target: {target}')
#             print(target)
#             print(f'Target Standard Deviation: {y_train.std()}')
#             print(models)
#             models.to_csv(f'{PARAM_DIR}/classification_results.csv', mode='a', header=False)
#         except:
#             print('Issue during lazypredict analysis')

#     model_name = 'tabnet'

#     # FastAI + pre-trained TabNet
#     #==============================================================================
#     learn = None
#     i = 0
#     while True:
#         try:
#             del learn
#         except:
#             pass
#         try:
#             learn = 0
#             model = TabNetModel(get_emb_sz(to), len(to.cont_names), dls.c, n_d=64, n_a=64, n_steps=5, virtual_batch_size=256)
#             # save the best model so far, determined by early stopping
#             cbs = [SaveModelCallback(monitor='_rmse', comp=np.less, fname=f'{model_name}_{PROJECT_NAME}_{target_str}_best'), EarlyStoppingCallback()]
#             learn = Learner(dls, model, loss_func=MSELossFlat(), metrics=rmse, cbs=cbs)
#             #learn = get_learner(to)
#             if(learn != 0):
#                 break
#             if i > 50:
#                 break
#         except:
#             i += 1
#             print('Error in FastAI TabNet')
#             traceback.print_exc()
#             continue
#     try:
#         #display learning rate finder results
#         x = learn.lr_find()
#     except:
#         pass
#     if AUTO_ADJUST_LEARNING_RATE == True:
#         FASTAI_LEARNING_RATE = x.valley
#     print(f'LEARNING RATE: {FASTAI_LEARNING_RATE}')
#     try:
#         if i < 50:
#             learn.fit_one_cycle(20, FASTAI_LEARNING_RATE)
#             plt.figure(figsize=(10, 10))
#             try:
#                 ax = learn.show_results()
#                 plt.show(block=True)
#             except:
#                 print('Could not show results')
#                 pass
#     except:
#         print('Could not fit model')
#         traceback.print_exc()
#         pass

#     #==============================================================================

#     #fit an xgboost model
#     #==============================================================================
#     if REGRESSOR == True:
#         xgb = XGBRegressor()
#     else:
#         xgb = XGBClassifier()
#     try:
#         xgb = XGBRegressor()
#         xgb.fit(X_train, y_train)
#         y_pred = xgb.predict(X_test)
#         print('XGBoost Predictions vs Actual==========')
#         print(pd.DataFrame({'actual': y_test, 'predicted': y_pred}).head())
#         print('XGBoost RMSE: ', np.sqrt(mean_squared_error(y_test, y_pred)))
#         #save feature importance plot to file
#         plot_importance(xgb)
#         plt.title(f'XGBoost Feature Importance for {PROJECT_NAME} | Target : {target}', wrap=True)
#         plt.tight_layout()
#         plt.show()
#         plt.savefig(f'{PARAM_DIR}/xgb_feature_importance_{target_str}.png')
#         fi_df = pd.DataFrame([xgb.get_booster().get_score()]).T
#         fi_df.columns = ['importance']
#         #create a column based off the index called feature
#         fi_df['feature'] = fi_df.index
#         #create a dataframe of feature importance
#         fi_df = fi_df[['feature', 'importance']]
#         fi_df.to_csv(f'{PARAM_DIR}/xgb_feature_importance_{target_str}.csv', index=False)
#         #xgb_fi = pd.DataFrame(xgb.feature_importances_, index=X_train.columns, columns=['importance'])
#         #xgb_fi.to_csv(f'{PARAM_DIR}/xgb_feature_importance_{target_str}.csv')
#         #print('XGBoost AUC: ', roc_auc_score(y_test, y_pred))
#     except:
#         traceback.print_exc()
#         print('XGBoost failed')

Target Variable: Profit_processed

CATS=====================
['Ship Mode', 'Segment', 'Country', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']
CONTS=====================
['City', 'Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed']
25
Looping through continuous variables to find breakpoint

Continuous variables that made the cut : ['City', 'Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed']
Categorical variables that made the cut : ['Ship Mode', 'Segment', 'Country', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed', 'City_na']

Target Variable: Discount_processed
CATS=====================
['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']
CONTS=====================
['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
26

Looping through continuous variables to find breakpoint

Continuous variables that made the cut : ['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
Categorical variables that made the cut : ['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']

Target Variable: Quantity_processed
CATS=====================
['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']
CONTS=====================
['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
26

Looping through continuous variables to find breakpoint

Continuous variables that made the cut : ['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
Categorical variables that made the cut : ['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']

Target Variable: Sales_processed
CATS=====================
['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']
CONTS=====================
['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Profit_processed']
25

Looping through continuous variables to find breakpoint

Continuous variables that made the cut : ['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Profit_processed']
Categorical variables that made the cut : ['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']

Target Variable: Sub-Category_processed
CATS=====================
['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']
CONTS=====================
['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
26

Looping through continuous variables to find breakpoint

Continuous variables that made the cut : ['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
Categorical variables that made the cut : ['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']

Target Variable: Category_processed
CATS=====================
['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']
CONTS=====================
['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
26

Looping through continuous variables to find breakpoint

Continuous variables that made the cut : ['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
Categorical variables that made the cut : ['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']

Target Variable: Region_processed
CATS=====================
['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']
CONTS=====================
['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
26

Looping through continuous variables to find breakpoint

Continuous variables that made the cut : ['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
Categorical variables that made the cut : ['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']

Target Variable: Postal Code_processed
CATS=====================
['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']
CONTS=====================
['Postal Code', 'Sales', 'Profit', 'Sales_processed', 'Profit_processed']
25

Looping through continuous variables to find breakpoint

Continuous variables that made the cut : ['Postal Code', 'Sales', 'Profit', 'Sales_processed', 'Profit_processed']
Categorical variables that made the cut : ['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']

Target Variable: State_processed
CATS=====================
['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']
CONTS=====================
['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
26

Looping through continuous variables to find breakpoint

Continuous variables that made the cut : ['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
Categorical variables that made the cut : ['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']

Target Variable: City_processed
CATS=====================
['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']
CONTS=====================
['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
26

Looping through continuous variables to find breakpoint

Continuous variables that made the cut : ['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
Categorical variables that made the cut : ['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']

Target Variable: Country_processed
CATS=====================
['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']
CONTS=====================
['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
26

Looping through continuous variables to find breakpoint

Continuous variables that made the cut : ['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
Categorical variables that made the cut : ['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']

Target Variable: Segment_processed
CATS=====================
['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']
CONTS=====================
['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
26

Looping through continuous variables to find breakpoint

Continuous variables that made the cut : ['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
Categorical variables that made the cut : ['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']

Target Variable: Ship Mode_processed
CATS=====================
['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']
CONTS=====================
['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
26

Looping through continuous variables to find breakpoint

Continuous variables that made the cut : ['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
Categorical variables that made the cut : ['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']

Target Variable: Profit
CATS=====================
['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']
CONTS=====================
['Postal Code', 'Sales', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
25

Looping through continuous variables to find breakpoint

Continuous variables that made the cut : ['Postal Code', 'Sales', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
Categorical variables that made the cut : ['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']

Target Variable: Discount
CATS=====================
['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']
CONTS=====================
['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
26

Looping through continuous variables to find breakpoint

Continuous variables that made the cut : ['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
Categorical variables that made the cut : ['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']

Target Variable: Quantity
CATS=====================
['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']
CONTS=====================
['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
26

Looping through continuous variables to find breakpoint

Continuous variables that made the cut : ['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
Categorical variables that made the cut : ['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']

Target Variable: Sales
CATS=====================
['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']
CONTS=====================
['Postal Code', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
25

Looping through continuous variables to find breakpoint

Continuous variables that made the cut : ['Postal Code', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
Categorical variables that made the cut : ['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']

Target Variable: Sub-Category
CATS=====================
['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']
CONTS=====================
['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
26

Looping through continuous variables to find breakpoint

Continuous variables that made the cut : ['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
Categorical variables that made the cut : ['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']

Target Variable: Category
CATS=====================
['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']
CONTS=====================
['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
26

Looping through continuous variables to find breakpoint

Continuous variables that made the cut : ['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
Categorical variables that made the cut : ['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']

Target Variable: Region
CATS=====================
['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']
CONTS=====================
['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
26

Looping through continuous variables to find breakpoint

Continuous variables that made the cut : ['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
Categorical variables that made the cut : ['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']

Target Variable: Postal Code
CATS=====================
['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']
CONTS=====================
['Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
25

Looping through continuous variables to find breakpoint

Continuous variables that made the cut : ['Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
Categorical variables that made the cut : ['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']

Target Variable: State
CATS=====================
['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']
CONTS=====================
['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
26

Looping through continuous variables to find breakpoint

Continuous variables that made the cut : ['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
Categorical variables that made the cut : ['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']

Target Variable: City
CATS=====================
['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']
CONTS=====================
['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
26

Looping through continuous variables to find breakpoint

Continuous variables that made the cut : ['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
Categorical variables that made the cut : ['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']

Target Variable: Country

CATS=====================
['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']
CONTS=====================
['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
26
Looping through continuous variables to find breakpoint

Continuous variables that made the cut : ['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
Categorical variables that made the cut : ['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']

Target Variable: Segment

CATS=====================
['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']
CONTS=====================
['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
26
Looping through continuous variables to find breakpoint

Continuous variables that made the cut : ['Postal Code', 'Sales', 'Profit', 'Postal Code_processed', 'Sales_processed', 'Profit_processed']
Categorical variables that made the cut : ['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category', 'Quantity', 'Discount', 'Ship Mode_processed', 'Segment_processed', 'Country_processed', 'City_processed', 'State_processed', 'Region_processed', 'Category_processed', 'Sub-Category_processed', 'Quantity_processed', 'Discount_processed']

CPU times: user 1min 35s, sys: 13.5 s, total: 1min 49s
Wall time: 1min 39s

# -- STEFANOS -- We have to disable the following too because even though it's Pandas code, it uses results from ML

In [21]:
# out_dir = f'./{PROJECT_NAME}'
# xgb_feature_importance_csvs = []

# for file in os.listdir(out_dir):
#     if 'xgb_feature_importance' in file and '.csv' in file:
#         xgb_feature_importance_csvs.append(pd.read_csv(os.path.join(out_dir, file)))

# xgb_feature_importance = pd.concat(xgb_feature_importance_csvs,axis=0)
# xgb_feature_importance.rename(columns={'Unnamed: 0': 'feature'}, inplace=True)
# print(xgb_feature_importance.head())
# xgb_feature_importance.groupby('feature')['importance'].mean().sort_values(ascending=False).plot(kind='bar', title='XGBoost Overall Feature Importance', figsize=(20, 10))

In [ ]:
pd_df = cudf.DataFrame().to_pandas()

In [ ]:
%%time
## Transfer_pre 11 ##
pd_df['Ship Mode'] = df['Ship Mode']

In [ ]:
%%time
## Transfer_pre 11 ##
pd_df['Segment'] = df['Segment']

In [ ]:
%%time
## Transfer_pre 11 ##
pd_df['Country'] = df['Country']

In [ ]:
%%time
## Transfer_pre 11 ##
pd_df['City'] = df['City']

In [ ]:
%%time
## Transfer_pre 11 ##
pd_df['State'] = df['State']

In [ ]:
%%time
## Transfer_pre 11 ##
pd_df['Postal Code'] = df['Postal Code']

In [ ]:
%%time
## Transfer_pre 11 ##
pd_df['Region'] = df['Region']

In [ ]:
%%time
## Transfer_pre 11 ##
pd_df['Category'] = df['Category']

In [ ]:
%%time
## Transfer_pre 11 ##
pd_df['Sub-Category'] = df['Sub-Category']

In [ ]:
%%time
## Transfer_pre 11 ##
pd_df['Sales'] = df['Sales']

In [ ]:
%%time
## Transfer_pre 11 ##
pd_df['Quantity'] = df['Quantity']

In [ ]:
%%time
## Transfer_pre 11 ##
pd_df['Discount'] = df['Discount']

In [ ]:
%%time
## Transfer_pre 11 ##
pd_df['Profit'] = df['Profit']

In [22]:
%%time
### cell 11 ###

df.isna().sum()

CPU times: user 32.5 ms, sys: 4.59 ms, total: 37.1 ms
Wall time: 32.3 ms

Ship Mode                 0
Segment                   0
Country                   0
City                      0
State                     0
Postal Code               0
Region                    0
Category                  0
Sub-Category              0
Sales                     0
Quantity                  0
Discount                  0
Profit                    0
Ship Mode_processed       0
Segment_processed         0
Country_processed         0
City_processed            0
State_processed           0
Postal Code_processed     0
Region_processed          0
Category_processed        0
Sub-Category_processed    0
Sales_processed           0
Quantity_processed        0
Discount_processed        0
Profit_processed          0
dtype: int64

# **To Be Continued...**